### ISSUE TITLE
Global Before/After mining scripts

### ISSUE THREAD

**Issue by Balzhur** [angelbbs/NiceHashMinerLegacy#10]
Would be nice to have global Before/After mining scripts for "regular" overclocking and overclocking reset.
E.G.:
1. Run global BeforeMining.cmd (from NHML root folder?) when user clicks "Start" or auto-mining starts.
2. Run specific miner scripts (from miner folder) if they exist and enabled - works now
3. Run global AfterMining.cmd (from NHML root folder?) when user clicks "Stop" or NHML exits.

This way we can achieve overclocking and overclocking reset "globally" and fine tune it for several specific miners instead of cloning Before/After scripts for every miner.

**Comment by angelbbs** [comment]
Не очень понятно, зачем это надо, если уже есть скрипты для каждого майнера.

**Comment by Balzhur** [comment]
@angelbbs чтобы не распихивать по два скрипта в папку каждого майнера.
Я предлагаю сделать два дефолтных скрипта,  в которых будет прописан глобальный оверклок, тогда можно иметь всего несколько в папках для майнеров.

**Comment by angelbbs** [comment]
Всё-равно непонятно. Для разных алгоритмов оперклок кардинально различается. Например, для эфира надо частоту ядра понизить, а память поднять. А для x16r наоборот. Т.е. должно выполняться 2 скрипта, в одном частоту память поднимаем, а во втором понижаем?

**Comment by Balzhur** [comment]
@angelbbs, забей, разжевал уже как мог.

**Comment by Balzhur** [comment]
Антон, с [моей версией BeforeMining.cmd](https://github.com/angelbbs/NiceHashMinerLegacy/wiki/%5BExample%5D-BeforeMining.cmd-overclock-script) можно таки заимплементить всего один оверклок скрипт чтобы не раскидывать его по подкаталогам майнеров. То есть - есть глобальный, значит юзаем его, иначе юзаем тот, что в подкаталоге с майнером. Если есть и тот и тот, ну фиг знает, значит либо оба выполнять либо только из каталога майнера.

**Comment by foxwarernd** [comment]
глобальный скрипт это классно. главное чтобы параметры передавались нормально. для каждых передаваемых параметров(номер видеокарты, алгоритм, майнер, частоты) можно прописать обработчик в едином скрипте.

**Comment by Balzhur** [comment]
@foxwarernd, частоты? шо? :)
Сейчас все норм передается, за исключением косяка с Phoenix - там номера видях увеличиваются на 1, почему-то. А все остальное что майнилось в последние пару месяцев (x16r, skunk, zhash) все красиво.

**Comment by foxwarernd** [comment]
Я пропустил? Сейчас передается в скрипт что нибудь в виде параметров и должно работать для всех майнеров nh? Читаю описание выпусков nh fix не видел подобного(вроде)
