### ISSUE TITLE
getting banned from stratnum servers

### ISSUE THREAD

**Issue by professor-jonny** [angelbbs/NiceHashMinerLegacy#11]
HI I tried your fork but I keep getting banned with certain algorithms and I have to renew my ip address.

**Comment by angelbbs** [comment]
Nicehash recommends that you use static IP

**Comment by foxwarernd** [comment]
I also have. ban temporary. in my case 1 day. The ban was given immediately as the test was run. since testing is done with your btc address - then I have a suspicion that this is the problem. I tried to test the ip with my hands - and there was no ban.

**Comment by angelbbs** [comment]
Wonderful! Its all?
