### ISSUE TITLE
Fan control in Overclock menu keep reverting to auto at 30% 

### ISSUE THREAD

**Issue by iMuhammadMustafa** [angelbbs/NiceHashMinerLegacy#113]
I keep trying to make it 75% and in the miner it's stuck at ~30% and when I recheck the settings it's set at Auto again for both cards. 

Is there an option to set up a custom fan curve or a way to keep it at the value I put?

**Comment by iMuhammadMustafa** [comment]
I found that I can set up the fan curve inside the MSI after burner and it persists

**Comment by WoonanThe** [comment]
will this issue be solved?
fan speed(%) not working, always resets to Auto, whatever you set
