### ISSUE TITLE
only 2 algos available

### ISSUE THREAD

**Issue by Dimitrovitsm** [angelbbs/NiceHashMinerLegacy#114]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7160935/log.txt)
i just unzip the nicehash fork fix 41.1,i made an exception for windows defender.but i still get a pop up about missing files .and when it lauches it has only 2 miners srbminer and xmrig.using  nvidia NON DCH DRIVERS.

**Comment by angelbbs** [comment]
select GPU first
