### ISSUE TITLE
3060 and 3080ti poor performance on dual mining

### ISSUE THREAD

**Issue by BTDXBIGTOMMYD** [angelbbs/NiceHashMinerLegacy#126]
So got a system with multiple cards running no issue. However the performance on the dual miners for both 3060 and 3080ti are very poor? 

Example 3080ti:
Auto (nbminer): 0.216
Dagger (gminer): 56

Dual dag/auto (Trex): 14.7/ 9.6

Is this purely to do with the setup of different miners vs that trex is overall poor for my cards in general?... O/C settings are setup for low core, power and additional memory (found that works for my cards the best)

![image](https://user-images.githubusercontent.com/88390062/137621780-7e2d1fe2-c8c1-437c-9d2d-c765fa9c97e8.jpeg)
![image](https://user-images.githubusercontent.com/88390062/137621785-4a01ac9f-db64-4bf9-8573-f603e9d1a5b2.jpeg)
![image](https://user-images.githubusercontent.com/88390062/137621793-85a50118-ab5c-4d8c-9c5c-dc17ee9b052f.jpeg)

**Comment by angelbbs** [comment]
set --lhr-tune 30 instead 68

**Comment by BTDXBIGTOMMYD** [comment]
> set --lhr-tune 30 instead 68

Well that didn't click for me 😅... Just done the 3060 and now it's in Boss mode!

Just reappying to the 3080ti and so far looking good.

Many thanks!
