### ISSUE TITLE
Перенос старых конфигов

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#13]
При обновлении версии как правильно перенести результаты тестирования со старой?
У меня всё время на новом пк пытается выкачать binы заново, заявляет что повреждена.
В некоторых случаях вообще пере затирает General.json и Benchmarks.
Каждый раз каждый алгоритм пере тестировать для каждой карты такое себе.

**Comment by angelbbs** [comment]
https://github.com/nicehash/NiceHashMinerLegacy/wiki/Getting-Started#-upgrading

**Comment by foxwarernd** [comment]
По сути удобства нет. Ссылка приведённая выше и так понятна.
Просто чтобы понимали - я скачал на одном ПК, скопировал на другой, а он там пошел себя еще раз выкачивать - бред.

**Comment by angelbbs** [comment]
При первом запуске скачиваются майнеры и это нормально

**Comment by foxwarernd** [comment]
понял
