### ISSUE TITLE
Downloading miners gets stuck at 80%

### ISSUE THREAD

**Issue by TimSirmovics** [angelbbs/NiceHashMinerLegacy#138]
I have tried:

- Disabling windows defender
- Adding NHML to exlcusion list
- Deleting miners.zip
- Waiting a long time

The log file is full of "No progress in ticks x" messages.

![image](https://user-images.githubusercontent.com/10243286/144764667-03e1e4a2-8889-4005-8918-2852a8d518ad.png)

![image](https://user-images.githubusercontent.com/10243286/144764683-ccaf0944-ebb9-4044-9dfc-dbcfb8a89c77.png)

**Comment by Ritik167** [comment]
i have the same problem if u have  solved the issue can u please help me

**Comment by TimSirmovics** [comment]
You can manually download miners.zip from the releases page, and unzip it into your install folder.

**Comment by Ritik167** [comment]
i unzipped still shows the same cn u help me with the path

**Comment by angelbbs** [comment]
Inzip this file https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip to the program folder with overwriting files
