### ISSUE TITLE
3080Ti не отображается как LHR карта

### ISSUE THREAD

**Issue by zarovavelfed** [angelbbs/NiceHashMinerLegacy#144]
Соответсвенно из-за этого пропали дуал майнинг алгоритмы
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775696/log.txt)
Прикладываю лог.

**Comment by angelbbs** [comment]
Скачайте и обновите программу еще раз

**Comment by zarovavelfed** [comment]
Чистая переустановка помогла, спасибо!
