### ISSUE TITLE
NHML не отображает степень нагрузки и потребление видеокарт

### ISSUE THREAD

**Issue by zarovavelfed** [angelbbs/NiceHashMinerLegacy#145]
![Снимок](https://user-images.githubusercontent.com/96649918/147382836-7df8987c-9a1d-4ea5-81dd-fa0fc202e435.PNG)
Прилагаю логи
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775701/log.txt)
[log_NvidiaGPUGetDataHost.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775702/log_NvidiaGPUGetDataHost.txt)
[monitor.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775703/monitor.txt)
В AIDA64 значения потребления отображаются

**Comment by angelbbs** [comment]
Попробуйте "чистую" (в новую папку) установку программы.

**Comment by zarovavelfed** [comment]
Чистую, это значит все данные бенчмарка и настройки разгонов по новой? У меня ж там солянка наборная из видеокарт)

**Comment by angelbbs** [comment]
Потом скопируйте папку configs из старой в новую

**Comment by zarovavelfed** [comment]
Чистая установка в новую папку не помогает

**Comment by zarovavelfed** [comment]
Прикладываю новые логи
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775814/log.txt)
[log_NvidiaGPUGetDataHost.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775815/log_NvidiaGPUGetDataHost.txt)
[monitor.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775816/monitor.txt)

**Comment by angelbbs** [comment]
OpenHardwareMonitor https://www.softportal.com/get-47555-open-hardware-monitor.html потребление показывает?

**Comment by zarovavelfed** [comment]
![Снимок](https://user-images.githubusercontent.com/96649918/147387263-99f76b06-21c5-4b48-b8ce-35e3f34d7947.PNG)
Что то не нахожу. AIDA64 точно показывает
![Снимок](https://user-images.githubusercontent.com/96649918/147387305-6f72831e-9042-4a80-89cc-54715fb117b3.PNG)

**Comment by angelbbs** [comment]
Замените файл nvml.dll из прилагаемого архива в папке C:\Program Files\NVIDIA Corporation\NVSMI или переустановите драйвера NVIDIA с удалением через DDU
[nvml.zip](https://github.com/angelbbs/NiceHashMinerLegacy/files/7775957/nvml.zip)

**Comment by zarovavelfed** [comment]
Ну чуть чуть полегчало
![Снимок](https://user-images.githubusercontent.com/96649918/147388437-18ad7194-61cf-4496-8141-baa843b98a59.PNG)
Но не до конца (DDU + новые дрова)

**Comment by zarovavelfed** [comment]
Я думаю, что помогло, а с 2070s я отдельно поговорю). Большое спасибо!
