### ISSUE TITLE
Auto switching trex dual mining not working

### ISSUE THREAD

**Issue by Moto828** [angelbbs/NiceHashMinerLegacy#149]
Auto switching only seems to work on single algorithms.

**Comment by angelbbs** [comment]
Everything works

**Comment by Moto828** [comment]
Downloaded a fresh copy but now no algos for GPU (3080LHR) are showing. RandomX is the only algo listed. Verified all miners have been downloaded to the Miners folder not sure why they are not showing.

**Comment by Moto828** [comment]
Disabled CPU detection  and now all GPU algos are showing.

**Comment by Moto828** [comment]
Fresh install is now working correctly. Thanks!
