### ISSUE TITLE
Can NiceHashMinerLegacy pass --server, --user, and --pass arguments entered in Extra Launch Parameters?

### ISSUE THREAD

**Issue by d-allin** [angelbbs/NiceHashMinerLegacy#151]
Hello.

This may be a feature request, unless it is already possible. It is also probably an edge case.

I am responsible for maintaining "shared" mining rigs where cards are owned by individuals, and the cards on one rig may be owned by more than one person.

I'd like to be able to mine on multiple mining pool logins or wallet addresses — on a per-card basis — by listing --server, --user, and --pass arguments in Extra Launch Parameters. If these arguments are not explicitly set in Extra Launch Parameters, then NHML should resort to its default behaviour and assign the info from the Bitcoin Address and Worker Name fields.

Can NiceHashMinerLegacy pass --server, --user, and --pass arguments entered in Extra Launch Parameters?

At the moment, I have NHML mining on the majority of the cards if one person owns most of the cards on a rig, and manual gminer/trex/etc instances running outside of NHML for the others. This does not allow for those cards to take advantage of algo switching, however.

I suppose a workaround would be allowing multiple instances. I will have to investigate that, but am curious if what I have asked about here is already possible or simple to add.

Thank you for your time and effort on maintaining this fork.

**Comment by angelbbs** [comment]
No, use multiple instances
