### ISSUE TITLE
Fan Speed missing for all my 3060ti cards - update 44

### ISSUE THREAD

**Issue by ChesterCheetos** [angelbbs/NiceHashMinerLegacy#158]
It is all in the title. Fan speeds not available since update 44, for all my 3060ti cards (both LHR and non-LHR) 
also effected is my single 1660 super. 

if log files are needed, let me know.

**Comment by angelbbs** [comment]
log files please

**Comment by ChesterCheetos** [comment]
[log_MiningRig1.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8001138/log_MiningRig1.txt)
[log_miningRig2.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8001139/log_miningRig2.txt)
[log_DesktopPC.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/8001140/log_DesktopPC.txt)

Just noticed, daggerAutolykos is gone as well for GPU2 in miningrig 2 and GPU1 in miningrig1. coincidentally those are the primary GPUs for those rigs. DaggerAutolykos is not gone on my Desktop for the primary GPU. All 3060Ti.

**Comment by angelbbs** [comment]
Download and install the program again

**Comment by ChesterCheetos** [comment]
All fan speeds issues fixed since build 20220204.13 was installed today.
