### ISSUE TITLE
Cryptonight v8 freeze up my pc

### ISSUE THREAD

**Issue by nazzier5463** [angelbbs/NiceHashMinerLegacy#16]
Mining cryptonight v8 sometimes freeze up my pc, not completely freeze, but few second only 3 - 5 second. It happens many time since mining cryptonight v8. Anyone having same issue as me ?

**Comment by Balzhur** [comment]
If you mine with GPU - this is normal for xmr-stak.

**Comment by 9301039** [comment]
у меня вообще после перехода на v8 комп вырубается через несколько часов работы, пока не думал даже как отлавливать проблему, думал в ближайшие дни майнер обновится а он что-то не обновляется, возможно я один такой, но криптекс обновился и показывает доходность практически такую же как и nhml, пора туда переходить они пофиксили проблему недозагрузки AMD о которой я им сообщал год назад ;)
