### ISSUE TITLE
Just started to use this last night.  I have several rigs but none of them could benchmark Octopus.

### ISSUE THREAD

**Issue by chilman408** [angelbbs/NiceHashMinerLegacy#160]
I have several mining rigs just got started with using this.  They are all Nvidia RTX 3070 and 3060.  None of these rigs could benchmark Octopus...  All ends in "Terminated".

Let me know how I can help to debug this?

**Comment by angelbbs** [comment]
Zip all the files in the LOGS folder after benchmark and send this to me

**Comment by chilman408** [comment]
Thanks so much.  Attached are the logs
[logs.zip](https://github.com/angelbbs/NiceHashMinerLegacy/files/8106550/logs.zip)
.

**Comment by angelbbs** [comment]
Inzip this file https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip to the program folder with overwriting files

**Comment by chilman408** [comment]
Works!  Thank you.
