### ISSUE TITLE
Getting this error in all of my rigs during startup - "missing miner files from last miner initialization..."

### ISSUE THREAD

**Issue by chilman408** [angelbbs/NiceHashMinerLegacy#161]
I can click the "No" response on the dialog box but otherwise NHML will get stuck at 85% launch.

This happens on everyone of my rigs.

**Comment by GR1Mk1ll3535** [comment]
Since the update to 45 exact same problem on all my rigs. Auto Update not working. Getting "Net Framework Error with Unhandled exception has occurred in your application". Miners doesn't update. Tried fresh download and miners separate also not working. Reverting to 44.0

**Comment by chilman408** [comment]
Same.  Tried manual download and install.  Did not fix it.

**Comment by phrozenspite** [comment]
Had the issue on 2 of my 3 systems.  Unsure what makes the other one different.  Manually downloading the miners and copying them to the folder before starting seemed to fix it

**Comment by GR1Mk1ll3535** [comment]
Have 6 Rigs, Only 1 worked now. All the other reverted back to 44.0. Will wait for updated fix.

**Comment by angelbbs** [comment]
Fixed. Download setup again.

**Comment by chilman408** [comment]
> Fixed. Download setup again.

...still same issue.

**Comment by angelbbs** [comment]
Press "Details" button on error window, copy the content and paste here

**Comment by chilman408** [comment]
Ok sorry, I reinstalled and copied the miner folder and now everything is working!
