### ISSUE TITLE
Share Above Target w/ Kawpow on Nicehash Auto

### ISSUE THREAD

**Issue by Jesso2k** [angelbbs/NiceHashMinerLegacy#175]
100% Rejected shares. All miners and resetting clocks recreate issue. Can be resolved by selecting Proxy Russia instead of Nicehash Auto.

*Miner Legacy Forkfix 48.2

**Comment by angelbbs** [comment]
![image](https://user-images.githubusercontent.com/11198603/181105347-f6a034cd-5a73-40b6-b467-30de251bd3a0.png)

**Comment by angelbbs** [comment]
On proxy-side all ok!
Disable settings - advanced - use proxy as failover server

**Comment by Jesso2k** [comment]
OK thank you, I'll leave it on Proxy Russia with failover server disabled in settings, if I'm understanding correctly. I saw there was an upcoming proxy fee attached in the release notes for 48.1, is that active yet?

**Comment by angelbbs** [comment]
yes, 0.75%

**Comment by Jesso2k** [comment]
Maybe using Nicehash Auto was an issue on Nicehash's side but it's fixed now, no proxy needed after the last few days.
