### ISSUE TITLE
ETHLargement

### ISSUE THREAD

**Issue by Balzhur** [angelbbs/NiceHashMinerLegacy#18]
Original NHML includes ETHlargement (under bin_3rdparty) which runs automatically with any ETH miner.
For example with 1080ti:
 - without ETHLargement -- 35 MH/s
 - with ETHLargement -- 48 MH/s

Did you remove it on purpose or it's just an oversight?
Please add it back if possible.

**Comment by foxwarernd** [comment]
try

**Comment by Balzhur** [comment]
@foxwarernd шта?

**Comment by foxwarernd** [comment]
я говорю - я обеими руками за!

**Comment by foxwarernd** [comment]
1) не со всеми картами работает
2) если есть карты которые не поддерживаются таблеткой и карты которые должны работать в одном риге то будут вылеты (например у меня с GTX 1080 и GTX 970 проблема запустить таблетку)
3) по идее можно стартовать таблетку через скрипт beforemining.cmd

**Comment by Balzhur** [comment]
@foxwarernd, таки да, вот это я туплю качественно... через beforemining запустить, через aftermining прибить, спасибо.
