### ISSUE TITLE
Разгон применяется по последней видеокарте

### ISSUE THREAD

**Issue by zarovavelfed** [angelbbs/NiceHashMinerLegacy#181]
Имею наборную солянку из 2060, 2070S, 3070, 3060Ti LHR, 3080Ti. Пытаюсь настроить разгон на алгоритме Octopus на NBMiner.
![image](https://user-images.githubusercontent.com/96649918/190851993-916265cd-4f42-4c10-ae29-60a9f89b9820.png)
![image](https://user-images.githubusercontent.com/96649918/190852004-fafd25bd-12f7-4e40-8e35-59b11df78ef1.png)
Однако результат такой, что настройки последнего адаптера применяются ко всем видеокартам
![image](https://user-images.githubusercontent.com/96649918/190852078-61aaf5fb-3abc-4657-9183-73dca5411742.png)
Как можно их разделить. Поймите меня 5 экземпляров NHML под каждую видеокарту запускать не вариант, тем паче если будет ребут (у меня автономная система), то запустится один экземпляр с бог его знает какими последствиями. Помогите пожалуйста!

**Comment by angelbbs** [comment]
Отключите галочку "Отключить проверку дополнительных параметров" или используйте разгон через MSI Afterburner во вкладке "Разгон"

**Comment by zarovavelfed** [comment]
Пробовал с галочкой. Ни в какую. а от MSI Afterburner толку мало. Через оболочку программы нельзя во вкладке разгон залочить частоту ядра, собственно как и pl

**Comment by zarovavelfed** [comment]
Кстати, если вы добавите такой функционал в раздел разгона, многие проблемы отпадут сами собой

**Comment by angelbbs** [comment]
В MSI Afterburner есть возможность лочить частоту, вольтаж и т.п. через редактор кривой.

**Comment by zarovavelfed** [comment]
Да в Msi есть, но ваша программа не позволяет это делать. Я пользуюсь вашим интеллектуальным продуктом как раз потому, что в нём есть возможность майнить на разных алгоритмах, а под каждый алгоритм разные настройки разгона и лока (по частоте ядра или повер лимита)

**Comment by zarovavelfed** [comment]
В любом случае, через параметры можно ли разграничить настройки разгона под каждую видюху, чтоб остальные тоже по своим параметрам стартовали? Если такого аргумента или возможности не имеется, не могли бы вы реализовать в разделе разгона (вкладка) lock по частоте ядра и по pl

**Comment by angelbbs** [comment]
1. Программа позволяет использовать кривую, смотрите видео.
2. Параметры применяются к карте, где они прописаны, если ОТКЛЮЧЕНА галочка "Отключить проверку дополнительных параметров"

**Comment by zarovavelfed** [comment]
Убрал галочку, результат тот же.  А где видео можно посмотреть?

**Comment by angelbbs** [comment]
Вкладка "Разгон"

**Comment by zarovavelfed** [comment]
Вы сами это видео то видели? Там эпилептическая дискотека

**Comment by zarovavelfed** [comment]
Разобрался. Большое спасибо за подсказку
