### ISSUE TITLE
KASPA mining through NH

### ISSUE THREAD

**Issue by Miiichal** [angelbbs/NiceHashMinerLegacy#183]
hello master...
is there a chance to implant **KASPA**? :)
thank you for a good work...

**Comment by angelbbs** [comment]
Ask this question to the nicehash team
https://www.nicehash.com/support

**Comment by Miiichal** [comment]
They had finally prepare it :)
https://www.nicehash.com/blog/post/kaspa-kheavyhash-is-now-supported-on-nicehash
