### ISSUE TITLE
On all my rigs with AMD cards, only the second card in a row shows the power, the others do not show power.

### ISSUE THREAD

**Issue by kadiev75** [angelbbs/NiceHashMinerLegacy#185]
On all my rigs with AMD cards, only the second card in a row shows the power, the others do not show power.

It doesn't matter if it's 5 cards or 8 it still has this problem
The problem does not exist with Nvidia cards

AMD Radion 6700 XT 
Driver version: 21.10.2
Windows IOT
Miner Legasy Fork Fix 53
All miners

![error](https://user-images.githubusercontent.com/73716841/205878070-8ac1fba3-9ac6-47ec-beaa-0aeb20a79dcc.jpg)

**Comment by kadiev75** [comment]
![2](https://user-images.githubusercontent.com/73716841/209800953-0e8944ca-56bc-4730-9c7b-9379593bdd27.png)

**Comment by angelbbs** [comment]
logs\log.txt

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10359335/log.txt)

**Comment by angelbbs** [comment]
"Settings"->"Advanced"-> Disable "Use OpenHardwareMonitor"

**Comment by kadiev75** [comment]
Now not even one is visible
![error2](https://user-images.githubusercontent.com/73716841/211011726-91829018-db1b-43aa-9bcc-64ad739c3571.png)
![error1](https://user-images.githubusercontent.com/73716841/211011728-e956500b-0e1c-4392-a1de-517205f54c95.png)

**Comment by angelbbs** [comment]
Unzip this arhive https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip to program folder with overwriting files

**Comment by kadiev75** [comment]
no change after placing the files,
I have 15 rigs and this bug is there on all of them where there are AMD cards


[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10360851/log.txt)
![Disable_OpenHardware](https://user-images.githubusercontent.com/73716841/211035921-8435b120-11b3-4602-be68-32fd5a4d8c77.png)
![Enable_OpenHardware](https://user-images.githubusercontent.com/73716841/211035927-4fe080ee-010c-47d8-921d-959af0040591.png)

**Comment by angelbbs** [comment]
Now Enable "Use OpenHardwareMonitor"

**Comment by kadiev75** [comment]
![Enable_OpenHardware](https://user-images.githubusercontent.com/73716841/211262395-71c857c6-ed54-46ce-a287-dd6c0b97e30a.png)
the second picture is with the option turned on

**Comment by kadiev75** [comment]
![Enable_LibreHardware](https://user-images.githubusercontent.com/73716841/211269376-e9b944f4-a149-4089-a1b5-04d5b0a2de7d.png)

**Comment by kadiev75** [comment]
![Enable_LibreHardware2](https://user-images.githubusercontent.com/73716841/211270166-ed49b01a-b893-4063-a207-5ef5d3a6e9fc.png)

**Comment by angelbbs** [comment]
Libre Hardware Monitor ->File ->Save report... 
and send LibreHardwareMonitor.Report.txt

**Comment by kadiev75** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10371841/LibreHardwareMonitor.Report.txt)

**Comment by kadiev75** [comment]
If you want, I can give you access to a rig so you can directly watch what you want?

**Comment by angelbbs** [comment]
1. Unzip this arhive https://disk.yandex.ru/d/2D6vF27wBg-r6Q to program folder with overwriting files
2. Some GPU do not give the required values, try installing a different version of amd drivers

**Comment by kadiev75** [comment]
![OK](https://user-images.githubusercontent.com/73716841/211295851-7ecafe02-2385-4d98-aa41-c5f8d25473bb.png)

It's not from the driver, it got fixed after I put the files, before that try a bunch of drivers :)
Thank you very much, you are great :)

**Comment by angelbbs** [comment]
Disable ZIL mining on gminer 3.24 in the settings. At the moment it has errors in the API which has a bad effect on profitability

**Comment by kadiev75** [comment]
I don't see any performance loss, but I turned it off because it doesn't help either :)

**Comment by kadiev75** [comment]
Hastily I was happy with the other rig, there is a problem again, I copied the files, the driver is the same, the cards in the rig are exactly the same, but it only shows the data in half.
I check with the GPU-Z program and there each card reports its sensors correctly.
I ran LibreHardware in parallel and it doesn't correctly report all sensors on all cards. That's the problem, I think

**Comment by kadiev75** [comment]
![lib1](https://user-images.githubusercontent.com/73716841/211314977-41fc0cee-e936-437f-a945-ba02535cafbb.png)

**Comment by kadiev75** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10373370/LibreHardwareMonitor.Report.txt)

**Comment by angelbbs** [comment]
Try disable "Use LibreHardwareMonitor"

**Comment by kadiev75** [comment]
![lib2](https://user-images.githubusercontent.com/73716841/211327452-d573fc9e-077f-42e7-a5c7-409d59dace1a.png)

**Comment by kadiev75** [comment]
Notice that the miner also shows all sensors

**Comment by angelbbs** [comment]
Пробуйте с выключеннрй опцией "Use Libre..." https://disk.yandex.ru/d/2D6vF27wBg-r6Q
Затем присылайте log.txt

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10374226/log.txt)
![lib3](https://user-images.githubusercontent.com/73716841/211339096-ebcec300-aefa-4b5f-b514-69d089cef4a3.png)

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10380054/log.txt)
![lib5](https://user-images.githubusercontent.com/73716841/211486927-fa16be49-6e4c-4452-8539-ac359b056e07.png)

**Comment by angelbbs** [comment]
OpenHardwareMonitor https://www.softportal.com/getsoft-47555-open-hardware-monitor-2.html показывает значения на всех gpu? Пришлите OpenHardwareMonitor.Report.txt

**Comment by kadiev75** [comment]
Yes this program reports all sensors correctly
[OpenHardwareMonitor.Report.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10381506/OpenHardwareMonitor.Report.txt)

**Comment by angelbbs** [comment]
Try https://disk.yandex.ru/d/2D6vF27wBg-r6Q and send log.txt

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10383222/log.txt)
![lib5](https://user-images.githubusercontent.com/73716841/211565725-2049d04a-37d2-4a37-9a7d-be1d0810b139.png)

**Comment by angelbbs** [comment]
disable "Use LibreHardwareMonitor"

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10383288/log.txt)
![lib6](https://user-images.githubusercontent.com/73716841/211567780-415ac695-ec4d-489a-a5f8-6c3e67161aab.png)

**Comment by kadiev75** [comment]
There is an improvement, the fans are visible

**Comment by angelbbs** [comment]
https://disk.yandex.ru/d/2D6vF27wBg-r6Q

**Comment by kadiev75** [comment]
![lib7](https://user-images.githubusercontent.com/73716841/211574660-8d4a8655-3aee-44d3-8f76-02dcfac42da1.png)

**Comment by angelbbs** [comment]
log.txt?

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10389939/log.txt)

**Comment by angelbbs** [comment]
https://disk.yandex.ru/d/2D6vF27wBg-r6Q

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10390866/log.txt)
![lib8](https://user-images.githubusercontent.com/73716841/211771767-932a9872-ca6c-4d84-95cd-ad7b5b245143.png)

it remains to show the power and it will be ok :)

**Comment by angelbbs** [comment]
https://disk.yandex.ru/d/2D6vF27wBg-r6Q

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10391222/log.txt)
![lib9](https://user-images.githubusercontent.com/73716841/211780790-681006cf-2a0d-43e5-9363-b3a852236803.png)

**Comment by kadiev75** [comment]
unchanged

**Comment by angelbbs** [comment]
https://disk.yandex.ru/d/2D6vF27wBg-r6Q

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10391589/log.txt)
![lib10](https://user-images.githubusercontent.com/73716841/211790184-361bd1b4-677a-4bb7-86fd-3d20f57eb4b5.png)

**Comment by angelbbs** [comment]
https://disk.yandex.ru/d/2D6vF27wBg-r6Q

**Comment by kadiev75** [comment]
![lib11](https://user-images.githubusercontent.com/73716841/211792376-8deab0e9-bd8d-4525-8a30-fa2f60701cfe.png)

Well done, now I will test on the other rigs and if everything is fine I will close the task :)

**Comment by angelbbs** [comment]
Try with the "Use Libre..." enabled

**Comment by kadiev75** [comment]
Everything seems ok here too
![lib12](https://user-images.githubusercontent.com/73716841/211794176-efdffdbb-a03e-4632-b142-0883fa0a6ebb.png)

**Comment by kadiev75** [comment]
Does it matter if it gets released or not?

**Comment by angelbbs** [comment]
Yes

**Comment by kadiev75** [comment]
![lib13](https://user-images.githubusercontent.com/73716841/211795341-b7e62750-d67b-4711-8295-b17abe0690d0.png)

It's ok on the other rig as well. I think that solved the problem :)
Leave them running LibreHardware options?
Will you release a new version or should I put the last one you sent me everywhere?

**Comment by angelbbs** [comment]
LibreHardware is better.
New version will be released in the next few days

**Comment by kadiev75** [comment]
Thank you very much you are great :)
If I can help I'm welcome :)

**Comment by kadiev75** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/10393405/log.txt)
![lib14](https://user-images.githubusercontent.com/73716841/211835767-004a314e-2235-4bd0-9ee3-10c56e35e189.png)

I found one rig where it doesn't work

**Comment by angelbbs** [comment]
Uninstall amd video drivers with DDU https://www.softportal.com/getsoft-32891-display-driver-uninstaller-1.html
then instal again

**Comment by kadiev75** [comment]
Everything is fine, thanks :)
