### ISSUE TITLE
Please add to the new Gminer 3.19  (--lock_mclock), useful to decrease power usage in Kaspa only mining mode

### ISSUE THREAD

**Issue by kadiev75** [angelbbs/NiceHashMinerLegacy#186]
Please add to the new Gminer 3.17  (--lock_mclock), useful to decrease power usage in Kaspa only mining mode

**Comment by kadiev75** [comment]
Gminer's Kaspa protocol for AMD is also missing

**Comment by angelbbs** [comment]
KHeavyHash (KASPA) not supported on AMD

**Comment by kadiev75** [comment]
10X :)
