### ISSUE TITLE
miniZ 2.3c

### ISSUE THREAD

**Issue by Miiichal** [angelbbs/NiceHashMinerLegacy#198]
hello team,
after changing miniZ in "miners" directory **from version 2.2c to the new one 2.3c** (with Karlsehash support downloadable from their site), it starts the mining window again, again, again... :)

**Comment by angelbbs** [comment]
show logs\log.txt

**Comment by Miiichal** [comment]
I tried to run a new version of NH, cause there is miniZ miner (with new version) automatically downloaded and loaded, but version 2.3c is still looping. After I rewrite with 2.2c it is OK and without problems
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/14725156/log.txt)

**Comment by Miiichal** [comment]
note, that this issue I have in all my rigs (RTX 3070, different types, vendors, configs, OC...)

**Comment by angelbbs** [comment]
What is the nvidia driver version? And show full log.txt after starting the program

**Comment by Miiichal** [comment]
522.25 and 531.79 (depends on rig, where i have Nicehash)

[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/14727650/log.txt)

**Comment by angelbbs** [comment]
Try 537.13 https://www.nvidia.com/download/driverResults.aspx/210648/en-us/

**Comment by Miiichal** [comment]
537.13 installed, but without success
When I change 2.3c to the older 2.2c so it works without problems :(
We can close it, if I am the only one with the problem, because no other joined :)

**Comment by angelbbs** [comment]
Try instal vc redistributable latest version 14.38.33135.0 (x64) https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by Miiichal** [comment]
14.38.33135 installed 22.03.2024
2.3c without success, 2.2.c is OK
...and with 537.13 I see around 7 pct rejected shares (Zelhash and Zhash) so I revert drivers back to 531.79 and see no rejected shares.
Should I have yet another driver? I found only posts on internet about most stable drivers 522.25 and 531.79...
So thats why I have them...

**Comment by angelbbs** [comment]
Run miniZ.exe from folder miners\miniz
Will there be an error message?

**Comment by Miiichal** [comment]
No error message, only black Window of miner (for about 1sec), just open and close, no text inside, it closes very fast.

And in log is:
[2024-03-23 11:41:18] [INFO] [NHM_API_info] Trying GetSmaAPICurrent
[2024-03-23 11:41:18] [INFO] [NHM_API_info] GetSmaAPICurrent OK
[2024-03-23 11:41:18] [INFO] [NHM_API_info] Trying GetSmaAPI24h
[2024-03-23 11:41:18] [INFO] [NHM_API_info] GetSmaAPI24h OK
[2024-03-23 11:41:20] [INFO] [MEMORY] Mem used: 93.8MB
[2024-03-23 11:41:20] [INFO] [NiceHash status] OK

Nothing more...

**Comment by angelbbs** [comment]
Run event viewer (eventvwr.msc) and find errors from miniz.exe in Application, located in Windows Logs folder.
https://eventlogxp.com/essentials/eventviewer.html

**Comment by Miiichal** [comment]
I think its something to do with standalone version 2.3c...
I tried to run it at home (where i dont mine, but have 2 months fresh new PC) and it does not start too.
Excavator only fast opens and closes. Without reporting error to eventviewer.
At home I have another driver version, another Windows etc, but it doesnt start too.
So maybe something wrong in miniZ.

**Comment by angelbbs** [comment]
Maybe, but you are the only one who reports this problem.

Is the version of Windows that you have installed original or pirated?

**Comment by Miiichal** [comment]
Its original with buyed serial number of course :)
Its not cracked or stolen...
As i said, other version of miniZ runs without problems, not the last one :(
