### ISSUE TITLE
Send algo name to BeforeMining.cmd

### ISSUE THREAD

**Issue by Balzhur** [angelbbs/NiceHashMinerLegacy#24]
Different algos for the same miner may need different overclocking, so if you send algo name to cmd one can implement different OC logic.

Разные алгоритмы в одном и том же майнере требуют разного оверклокинга. Если сделать чтобы в скрипт передавался еще и алгоритм, то можно настроить разный оверклокинг внутри скрипта для разных алгоритмов. Например тот же CryptoDredge - x16r лучше майнится когда + в ядро, skunk когда + в ядро и - в память, CNv8: + в ядро и + в память, причем везде разные + и PowerLimit...

Надеюсь понятно изложил, если что - спрашивай.

**Comment by foxwarernd** [comment]
не только алгоритм, но и список задействованных видеокарт

**Comment by Balzhur** [comment]
@foxwarernd в принципе, да, об этом я подумал уже после того как написал запрос. Алгоритм Антон уже добавил :)

**Comment by Balzhur** [comment]
@angelbbs, бывает на разные видяхи запускаются разные майнеры, например у меня сегодня пол-дня 1080 майнила skunk, а 1070 - x16r еще и разными майнерами. При этом оверклок, естественно, "перезаписывается" из последнего записанного майнера. Если передавать еще и номер видяхи, то можно будет в скрипте еще правило дописать, но какой же это гимор на виндовом cmd....

**Comment by Balzhur** [comment]
@angelbbs, я вижу ты закоммитил. Есть поправочка - список видеокарт нужно передавать в кавычках, ибо потом его никак не распарсить внутри cmd.
То есть `BeforeMining.cmd NVIDIA SINGLE x16r "0,1,3,5"`

Логику я уже нарисовал, как-то так в очень сокращенном (только Nvidia) варианте:
```
@echo off
SetLocal EnableDelayedExpansion
rem ****************************************************************************************
rem * Set RUN on TRUE to enable this command scrypt
rem * Установите параметр RUN в TRUE, что бы включить выполнение этого коммандного файла
rem ****************************************************************************************
SET RUN=TRUE

rem ****************************************************************************************
rem * Установите параметр NOVISIBLE в TRUE, что бы скрыть окно выполнения этого коммандного файла
rem * Set NOVISIBLE on TRUE to hide command window
rem ****************************************************************************************
SET NOVISIBLE=TRUE

SET LOG=logs/nhml.log
SET MINER=T-Rex
SET PLATFORM=%1
SET MMODE=%2
SET ALGO=%3
SET DEVLIST=%~4

if "%PLATFORM%"=="AMD" goto amd
if "%PLATFORM%"=="NVIDIA" goto nvidia
goto :end

:nvidia
if "%MMODE%" EQU "DUAL" goto nvidiadual
echo NVIDIA

FOR %%G IN (%DEVLIST%) DO (
	set GPU=%%G
	echo GPU:  !GPU!
	echo Algo: %ALGO%

REM *** Call OC subroutine with "CoreClock MemoryClock PowerTarget" as parameters ***
IF "%ALGO%"=="x16r" (
	if "!GPU!"=="0" call :OC 150 0 65
	if "!GPU!"=="1" call :OC 140 0 70

) ELSE IF "%ALGO%"=="skunk" (
	if "!GPU!"=="0" call :OC 170 -502 65
	if "!GPU!"=="1" call :OC 150 -600 70

) ELSE (
	echo Undefined Algorithm=%ALGO%, Default OC & SET ALGO=default
	if "!GPU!"=="0" call :OC 110 450 65
	if "!GPU!"=="1" call :OC 110 450 65
))
goto :end

:amd
goto :end

:OC
SET CORECLOCK=%1
SET MEMCLOCK=%2
SET PT=%3
echo "[INFO] OverClock for %MINER% %ALGO%: GPU%GPU% core=%CORECLOCK% memory=%MEMCLOCK% power=%PT%" >> %LOG%
nvidiaInspector.exe -setBaseClockOffset:%GPU%,0,%CORECLOCK% -setMemoryClockOffset:%GPU%,0,%MEMCLOCK% -setPowerTarget:%GPU%,%PT%
GOTO:EOF

:end
echo end
rem Do NOT disable this delay
timeout /t 1 /nobreak
exit
```

**Comment by foxwarernd** [comment]
В правильном направлении идёте, товарищи!

**Comment by Balzhur** [comment]
@angelbbs можешь тестовую сборку сделать, пожалуйста? Я задолбался каждый раз править кучу case sensitive имен в проекте и вчера не мог собрать из-за проблем с AMDOpenCL... (да я чайник в С и в сборке под винды).

**Comment by Balzhur** [comment]
В общем, у меня все работает отлично. Спасибо :) Пришлось компилить самому.

**Comment by foxwarernd** [comment]
а нам чайникам ждать следующего билда (
вот бы всё это, да ещё и майнеры обновить

**Comment by Balzhur** [comment]
@foxwarernd, я тоже чайник. Компилил через пень-колоду.
А майнеры тебе никто не мешает обновить, просто скачай и распакуй в нужную папку, отличий в синтаксисе запуска там нет.

**Comment by Balzhur** [comment]
Implemented in FF10. Closing.
