### ISSUE TITLE
Дополнительные параметры

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#26]
в некоторых случаях зачем то говорят писать в начале "%", т.е. например "%-i 8"
как правильно прописывать дополнительные параметры?

**Comment by angelbbs** [comment]
% в начале строки доп.параметров  отключает проверку корректности этих параметров.  В этом случае, всё, что передано после символа %, отправляется в строку запуска майнера. Это можно посмотреть в логе ))

**Comment by foxwarernd** [comment]
спасибо!
