### ISSUE TITLE
Latest build

### ISSUE THREAD

**Issue by angelbbs** [angelbbs/NiceHashMinerLegacy#29]
https://github.com/angelbbs/NiceHashMinerLegacy/blob/master/LatestBuild/nhmlffLatest.zip

**Comment by 9301039** [comment]
http://prntscr.com/le20gk

**Comment by 9301039** [comment]
windows 8.1 64bit

**Comment by angelbbs** [comment]
update .net framework

**Comment by 9301039** [comment]
у меня последняя версия http://prntscr.com/lejjyn

**Comment by foxwarernd** [comment]
чисто при скачивании из этого архива не стартует.
 в логах пишет Lang error: Не удалось найти часть пути "C:\mining\nhmlffLatest\langs"
подкинул папку langs из fix 10 и запустилась.

а теперь вопрос - что нового в этом билде?

**Comment by sinnx3** [comment]
Does this fix the program crashing when trying to benchmark? 

IE: benchmarking daggerhashimoto, program crashes and all benchmark data for all algo's are lost/wiped causing you to rebenchmark into a loop?
