### ISSUE TITLE
lolminer don´t recognize my AMD cards correctly

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#33]
I´ve 4 different cards in my rig and if I benchmark or run the lolminer, the lolminer take every time the first card (id 2) of my setup. Therefore is the zhash algorithm unusable at this time ....

**Comment by angelbbs** [comment]
yes. I know this issue. its was resolved with new version of lolminer, hope

**Comment by PeDa1** [comment]
The currently latest lates version, lolMiner 0.6 alpha 4, unfortunately no.

**Comment by nomemega** [comment]
Я побывал карты амд нехотяи

**Comment by angelbbs** [comment]
yes. unpack this file into old folder

**Comment by angelbbs** [comment]
@nomemega Какие карты, как именно не хотят?

**Comment by nomemega** [comment]
580 lolminer перезапускаеться майнер

**Comment by nomemega** [comment]
И майнер непаказыввет мои карты только паказывает nvidia

**Comment by PeDa1** [comment]
> 
> 
> try this build, please https://yadi.sk/d/FbOuJVU67GAzwQ

Unfortunately don´t help a lot, still the same problem.

**Comment by angelbbs** [comment]
@PeDa1 Please send me log.txt and log.1.txt files from LOGS folder

**Comment by PeDa1** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2663492/log.txt)
[log.1.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2663493/log.1.txt)

**Comment by nomemega** [comment]
так решил проблему определение видео карт отключил в диспетчере задач. карты Nvidia  майнер стал определять карты AMD  работают обе,но стоит подключить карты Nvidia неработает доходит до перезагрузки

**Comment by angelbbs** [comment]
Unfortunately, at moment I can't fix this issue until lolMiner developer changes the way GPU enumeration.
In some mixed rigs (AMD and NVIDIA) lolMiner can incorrectly GPU enumeration.

**Comment by PeDa1** [comment]
New version has been released, can you test it please?
https://github.com/Lolliedieb/lolMiner-releases/releases/tag/0.6

**Comment by angelbbs** [comment]
@PeDa1 in my mixed rig all gpu's enumerating correctly on any lolminer version

**Comment by angelbbs** [comment]
@PeDa1 yes

**Comment by PeDa1** [comment]
So, i´ve tested the final 0.6 and what should I say it works! The GPU enumeration works fine for me!

**Comment by woodyalien** [comment]
Im having same issue with lolminer and gminer, but I see that this thread is old, I must suppose that the correction mentioned above is already incorporated into 13.1?
