### ISSUE TITLE
Auto-update benchmarks and power consumption periodically

### ISSUE THREAD

**Issue by Balzhur** [angelbbs/NiceHashMinerLegacy#34]
En: Is it possible to implement automatic update of values in benchmark files, namely BenchmarkSpeed and PowerUsage. Optionally, please, like add new option to config file to switch it on/off.

Ru: видел такое в nemos miner - во время майнинга скорость периодически записывается в конфиг, таким образом отпадает необходимость перебечивать при выходе новой версии майнера или изменении разгона. Туда же сразу писать энергопотребление. Но надо как-то все это усреднять, особенно для "прыгучих" алгоритмов типа x16. Получится сделать или DillonN не оставил вариантов? :)
Его просить бесполезно, он на тикеты вообще забил год назад. Опционально, чтоб можно было эту фичу включить-выключить в конфиге.

**Comment by angelbbs** [comment]
Теоретически это можно сделать, но потребует масштабных изменений в разборе ответов API во всех майнерах. И, если мне память не изменяет, в каких-то майнерах нет ответа API по каждой карте, а выдается общий хешрейт. Но могу ошибаться, надо проверять.

**Comment by Balzhur** [comment]
@angelbbs на те, которые не отдают по каждой карте, забить :)

**Comment by angelbbs** [comment]
С другой стороны, это не всегда может быть полезно. Например t-rex на skunk при старте на 5х1063 выдает общий хешрейт 132, а потом снижается до 130

**Comment by Balzhur** [comment]
@angelbbs у меня то же самое, в данный момент выхожу из положения парся лог и высчитывая average в Excel :). Поэтому и пишу, что надо как-то усреднять. Например, записывать значения выдаваемые api майнера куда-то, потом считать среднее за час/сутки (а лучше сделать интервал за который считается среднее настраиваемым) и апдейтить бенчмарк.
Понимаю, что это много работы...

**Comment by angelbbs** [comment]
Могу пока сделать выгрузку хешрейта в csv файлы, чтоб потом его можно было скриптом распарсить или макросом в экселе обработать и записать в бенч

**Comment by Balzhur** [comment]
Смысл в том чтоб без доп. скриптов, макросов и экселей, сразу в файл бенчмарка.
А так я и сам могу :)

**Comment by angelbbs** [comment]
Еще  момент... К примеру, обновился cryptodredge и стал выдавать на 10% больше, чем t-rex. А пока бенч не пройден, то он никогда не запустится, будет t-rex копать. Так что полной автоматизации не получится.

**Comment by Nicheuji** [comment]
What's the conclusion in English? :D

**Comment by angelbbs** [comment]
will be implemented in future versions
