### ISSUE TITLE
Не закрываются окна Zhash

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#36]
Переключается автоматом на Zhash, потом на что-нибудь другое. Но окна Zhash не закрываются

![image](https://user-images.githubusercontent.com/19841581/50005656-2b49ee00-ffbc-11e8-9573-0c6fa22ec1c3.png)

**Comment by angelbbs** [comment]
На версии 11.1?

**Comment by foxwarernd** [comment]
11.0
