### ISSUE TITLE
Before & After mining script Extra options

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#42]
RUS:
При вызове скрипта Before & After mining для майнера "claymore_dual" некорректно передаётся номер видеокарты. Например в четвёртом параметре (список видеокарт) - ожидаю "0", а получаю "-platform 2 -di 0".
Что может быть не так?

ENG:
When calling the Before & After mining script for the "claymore_dual" miner, the video card number is incorrectly transmitted. For example, in the fourth parameter (a list of video cards) - I expect "0", but I get "-platform 2 -di 0".
What could be wrong?

**Comment by angelbbs** [comment]
Исправлено в https://github.com/angelbbs/NiceHashMinerLegacy/blob/master/LatestBuild/nhmlffLatest.zip
https://github.com/angelbbs/NiceHashMinerLegacy/issues/41

**Comment by foxwarernd** [comment]
Спасибо!
Thanks!
