### ISSUE TITLE
 missing files before and after cmd

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#43]
ENG:
The files BeforeMining.cmd and AfterMining.cmd disappeared in the miner folders during the new launch. for example, take the miner t-rex from "NHML.Fork.Fix.11.1 \ bin_3rdparty \ t-rex" - these files do not exist. I downloaded separately manually "bin_3rdparty_ff11_1.zip" and "bin_ff11_1.zip" - they are not in the archives. The question is - under what conditions do these files appear in miner folders?

RUS:
Пропали файлы BeforeMining.cmd и AfterMining.cmd в папках майнеров при новом запуске. например взять майнер t-rex из "NHML.Fork.Fix.11.1\bin_3rdparty\t-rex" - этих файлов нет. Скачал отдельно вручную "bin_3rdparty_ff11_1.zip" и "bin_ff11_1.zip" - в архивах их нет. Вопрос - при каких условиях эти файлы появляются в папках майнеров?

**Comment by angelbbs** [comment]
@foxwarernd При первом запуске и остановке майнера
