### ISSUE TITLE
error running Phoenixminer

### ISSUE THREAD

**Issue by DK984** [angelbbs/NiceHashMinerLegacy#44]
it worked a few times but stopped. I have windows defender disabled entirely but I see hardware blocking msgs pop up.

GPU6: Allocating DAG (2.90) GB; good for epoch up to #243
GPU1: Allocating DAG (2.90) GB; good for epoch up to #243
GPU3: Allocating DAG (2.90) GB; good for epoch up to #243
GPU2: Allocating DAG (2.90) GB; good for epoch up to #243
GPU1: Generating DAG for epoch #241
GPU6: Generating DAG for epoch #241
CUDA error in CudaProgram.cu:102 : an illegal memory access was encountered (700)
CUDART error in CudaProgram.cu:188 : an illegal memory access was encountered (77)
GPU2 initMiner error: an illegal memory access was encountered
GPU6 initMiner error: an illegal memory access was encountered
CUDA error in CudaProgram.cu:102 : an illegal memory access was encountered (700)
GPU3 initMiner error: an illegal memory access was encountered
CUDART error in CudaProgram.cu:188 : an illegal memory access was encountered (77)
GPU1 initMiner error: an illegal memory access was encountered
CUDA error in CudaProgram.cu:64 : an illegal memory access was encountered (700)
GPU5 initMiner error: an illegal memory access was encountered
CUDA error in CudaProgram.cu:64 : an illegal memory access was encountered (700)
GPU4 initMiner error: an illegal memory access was encountered
Thread(s) not responding. Restarting.

**Comment by angelbbs** [comment]
1060 3GB?

**Comment by PBJellytime** [comment]
I'm getting the same error with 1060 6gb cards

**Comment by angelbbs** [comment]
https://bitcointalk.org/index.php?topic=2647654.msg34976064#msg34976064

**Comment by foxwarernd** [comment]
You may need to decrease the memory overclock. The new CUDA kernels are utilizing the GPU more fully, which may lead to such problems when the overclocks are on the edge of stability. Another possible remedy is to try and force the cards to be in P0 performance state instead of P2, which by some accounts makes them more stable at high overclocks.
