### ISSUE TITLE
Release 12, where BEAM and Grin mining with AMD ???

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#46]
Thank you for the new release but I don´t see the above new mining opportunities on AMD cards ....

**Comment by deeppurple1968** [comment]
И у меня тоже самое...

**Comment by angelbbs** [comment]
no AMD miners are compatible with nicehash yet

**Comment by PeDa1** [comment]
Even no the newest lolminer Alpha 4? Thats to bad .... :(

**Comment by angelbbs** [comment]
Lolliedieb post: 

Sry for the silence here, 
had some rough days (flu & fever) ... 
Hope to have alpha 5 for you next 2-3 days including support for NiceHash and some improvements for the scheduling (for some users alpha 2 was quicker then alpha 4 - thats going to be fixed)
Hope to be back with good news

**Comment by PeDa1** [comment]
Sounds good! :)

By the way, the original legacy miner use the B-Miner for Beam mining on AMD may you can implement it too.

**Comment by PeDa1** [comment]
lolMiner Alpha 5 with Nicehash support has been released, please add them as soon as possible.

Thanks,

**Comment by nomemega** [comment]
а когда доделаете  GrinCuckatoo31

**Comment by angelbbs** [comment]
на форуме есть 12.2 test #2

**Comment by PeDa1** [comment]
Sorry, I dont understand. Should be there a link to the 12.2 test ?

**Comment by angelbbs** [comment]
https://mega.nz/#!iZ4U1YhA!vjt2EXIaXQxNEkK9iyQ_Bxfz2ccQOIiQlhyfZtYCHrQ

**Comment by PeDa1** [comment]
Thanks, so far works great on my system. 👍 
And is there a chance for Grin mining on AMD? miners are availiable but they are compatible to Nicehash?

**Comment by angelbbs** [comment]
@PeDa1 maybe later
