### ISSUE TITLE
Gminer in Fork Fix 12 Invalid Nonce

### ISSUE THREAD

**Issue by PBJellytime** [angelbbs/NiceHashMinerLegacy#47]
After running for a while Gminer starts producing error messages

4:05:31 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:05:33 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:05:33 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:05:33 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:05:34 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:05:36 Temperature: GPU4 55C GPU0 62C GPU1 64C GPU2 59C GPU3 60C
14:05:36 Speed: GPU4 16.8 Sol/s GPU0 12.3 Sol/s GPU1 12.6 Sol/s GPU2 11.9 Sol/s GPU3 10.8 Sol/s
14:05:36 Power: GPU4 115W 0.15 Sol/W GPU0 76W 0.16 Sol/W GPU1 76W 0.17 Sol/W GPU2 75W 0.16 Sol/W GPU3 74W 0.15 Sol/W
14:05:36 Total Speed: 64.3 Sol/s Shares Accepted: 170 Rejected: 17 Power: 416W 0.15 Sol/W
14:05:36 Uptime: 0d 00:09:00 Electricity: 0.062kWh
14:05:38 New Job: 1704194324060 Difficulty: 134217728
14:05:55 New Job: 1704194326236 Difficulty: 134217728
14:06:01 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:06:04 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:06:06 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
14:06:06 Temperature: GPU4 56C GPU0 62C GPU1 64C GPU2 59C GPU3 59C
14:06:06 Speed: GPU4 16.6 Sol/s GPU0 10.6 Sol/s GPU1 11.7 Sol/s GPU2 10.8 Sol/s GPU3 11.3 Sol/s
14:06:06 Power: GPU4 115W 0.14 Sol/W GPU0 76W 0.14 Sol/W GPU1 75W 0.16 Sol/W GPU2 75W 0.14 Sol/W GPU3 75W 0.15 Sol/W
14:06:06 Total Speed: 61.0 Sol/s Shares Accepted: 170 Rejected: 20 Power: 416W 0.15 Sol/W
14:06:06 Uptime: 0d 00:09:30 Electricity: 0.066kWh
14:06:07 Share Rejected: Invalid nonce; is miner not compatible with NiceHash?

**Comment by Joshwaa2010** [comment]
Same problem here. It is intermittent.

**Comment by PBJellytime** [comment]
> Same problem here. It is intermittent.

Does it come and go?  I've only just noticed it and disabled the algo

**Comment by Joshwaa2010** [comment]
Yes it worked fine all last night then this morning it has gone down twice.

**Comment by Joshwaa2010** [comment]
> > Same problem here. It is intermittent.
> 
> Does it come and go? I've only just noticed it and disabled the algo

Make that 3 times now. I am not sure if it is Nicehash or the miner.

**Comment by Joshwaa2010** [comment]
Just saw this on Nicehash Twitter

Notification for all #BEAM miners: #gminer does not fully support our stratum protocol, thus you may see rejected shares. We are looking for alternative miners.

**Comment by PeDa1** [comment]
Hmm, I got the same failure on my AMD cards during BEAM mining. The official legacy gui provide BEAM mining on AMD with B-miner.

I think that is more a problem from Nicehash not from the miner in general.

**Comment by Joshwaa2010** [comment]
If you run the miner manually it will work. You have to run an instance per gpu. That's my workaround for now. If you run Fork fix you can select just one gpu to run BEAM and it will work.

**Comment by rainbowfc** [comment]
I still have rejected shares problem.. how did you fix it PeDa1?

**Comment by PeDa1** [comment]
Honestly, I do nothing for that. Suddenly I got almost no rejected shares (<1%) anymore on nVidia. Don't forget, Bminer produce some reject shares anyway. That seems to be normal.

**Comment by rainbowfc** [comment]
you told that you were getting this error with AMD cards.. maybe this issue is specific on AMD cards? are you using bminer seperately or NHM?

**Comment by angelbbs** [comment]
NHML Fork Fix 12.1 test
https://yadi.sk/d/G5pFjlVAtjSYAw
password: 123

**Comment by nomemega** [comment]
ШТО ТАМ

**Comment by nomemega** [comment]
> Тест NHML Fork Fix 12.1 
> https://yadi.sk/d/G5pFjlVAtjSYAw
> пароль: 123

а што там

**Comment by PeDa1** [comment]
> 
> 
> NHML Fork Fix 12.1 test
> https://yadi.sk/d/G5pFjlVAtjSYAw
> password: 123

Thanky, whats new?

**Comment by angelbbs** [comment]
@nomemega Lyra2REv3 algo

**Comment by PeDa1** [comment]
> 
> 
> @nomemega Lyra2REv3 algo

Puhh nice profitabilty but very hungry algorithm.

**Comment by PBJellytime** [comment]
Can't seem to download it? It doesn't help that I can't speak or write Russian :p
