### ISSUE TITLE
Nicehash Grin pools active, but pool address in current version is wrong

### ISSUE THREAD

**Issue by italianoch** [angelbbs/NiceHashMinerLegacy#48]
Hello, it looks like Nicehash has 2 Grin pools up, GrinCuckaroo29 and GrinCuckatoo31. I had Grin checked on my GPUs so they would start mining it when the SMA reported profitability, but it looks like the pool addresses that Gminer tries to connect to for Grin is incorrect. 
Is there a way to manually change the pool listing that NHML uses for Grin in the meantime while you incorporate this fix?

**Comment by angelbbs** [comment]
NH grin pools not working yet. Its NH problem

**Comment by italianoch** [comment]
Ah okay. That makes sense as the pool hashrates show 0. I had assumed the pool addresses for Grin in fork fix we’re incorrect as Nicehash lists them as “stratum+tcp://grincuckaroo29.LOCATION.nicehash.com:3371” and “stratum+tcp://grincuckatoo31.LOCATION.nicehash.com:3372”, but Gminer tries to connect to a different pool address.

**Comment by angelbbs** [comment]
stratum+tcp://grincuckaroo29.eu.nicehash.com:3371 if location sets to Europa server...

**Comment by italianoch** [comment]
Yes i’m aware The LOCATION gets replaced with the actual stratum location, such as usa, eu, hk. But Gminer tries to connect to “stratum://grin.eu.nicehash.com:3371” when the pool address is listed on Nicehash as “stratum://grincuckaroo31.eu.nicehash.com:3371”.
