### ISSUE TITLE
grin refusing to benchmark

### ISSUE THREAD

**Issue by ejonesss** [angelbbs/NiceHashMinerLegacy#49]
i am getting unable to initialize miner for gpu gtx 1060 6gb

+----------------------------------------------------------------+

|                          GMiner v1.25                          |

+----------------------------------------------------------------+

Algorithm:          Cuckaroo 29 "Grin"

Stratum server #1:  

  host:             stratum://grin.sparkpool.com:6666

  user:             angelbbs@mail.ru/bench_g

  password:         x

Stratum server #2:  

  host:             stratum://grin.eu.nicehash.com:3371

  user:             wallet address.worker1

  password:         x

Stratum server #3:  

  host:             stratum://grin.hk.nicehash.com:3371

  user:             wallet address.worker1

  password:         x

Power calculator:   on

Color output:       off

Watchdog:           on

API:                off

Log to file:        0_log.txt

Selected devices:   GPU0

Temperature limits: 90C 

------------------------------------------------------------------

17:27:15 Failed to initialize miner on GPU0: EVGA GeForce GTX 1060 6GB: 

17:27:15 No devices for mining

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by angelbbs** [comment]
417.71

**Comment by ejonesss** [comment]
yes i have that driver installed  do i need to downgrade or upgrade and to what version.

also now i am getting beam incompatible with nicehash.

**Comment by ejonesss** [comment]
i now have the latest once again with 12.1 with the same driver as above and still no grin

did you even fix grin in 12.1?

**Comment by angelbbs** [comment]
8 GB GPU RAM minimum for Grin

**Comment by ejonesss** [comment]
in a future program can you make grin work spill over into virtual memory?

or can increasing the virtual memory get it to work?

**Comment by ejonesss** [comment]
update:  i have read that c29 can run on 6gb card

https://old.reddit.com/r/gpumining/comments/ajtfey/my_gtx_1060_6gb_grin_coin_mining_results/

do i have to manually configure the miner and run it from a grin pool?

**Comment by angelbbs** [comment]
gminer does not support 1060 6 GB.
bminer will not be added to the program.

**Comment by ejonesss** [comment]
does the bminer support the 1060?  or what is the minimum card that will support gminer?

**Comment by ejonesss** [comment]
can i just replace the gminer with the bminer in the 3rd party folder and configure it to work?

according to the bminer site grin does 3.20 G/s on GTX 1060 6G.

**Comment by ejonesss** [comment]
update: i just downloaded the bminer and tested the grin batch file and no complaints so it looks like it supports the 1060 6gb so can i just replace the g miner with the b miner?

**Comment by ejonesss** [comment]
what cards do you support?

**Comment by angelbbs** [comment]
@ejonesss 1070-1080 and 20xx series

**Comment by ejonesss** [comment]
update: other user(s) on nicehash is having the same problem with gminer and it is the 1070 8gb that is not being used

https://old.reddit.com/r/NiceHash/comments/an3izp/new_release_nicehash_miner_legacy_19012/

**Comment by angelbbs** [comment]
I have a 1070 work fine in Windows 7
