### ISSUE TITLE
[Feature] advanced startup features

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#5]
ENG:
in the settings -> device tab and algorithms, I would like to have two fields when selecting each algorithm - in these fields you can add commands (or command files). Two fields - one before running the algorithm's mining, the second after the completion of this algorithm's completion. These fields can be used for example for overclocking (at least I would use) through third-party utilities. For example, for eth mining on nvidia, it's best to overclock the GPU processor and reduce the memory frequency of the GPU - you can make one command through Nvidia Inspector. I tried to use the startup options built into the miners to overclock the GPU - but this does not always work correctly.

RUS:
в настройках -> вкладка устройства и алгоритмы хотелось бы иметь два поля при выборе каждого алгоритма - в этих полях иметь возможность добавлять команды (или командные файлы). Два поля - одно перед запуском майнинга алгоритма, второе после завершения майнинга этого алгоритма. Эти поля можно будет использовать например для разгона (по крайней мере я бы использовал) через сторонние утилиты. Например для майнинга eth на nvidia лучше всего выставлять разгон процессора GPU и снижать частоты памяти GPU - можно сделать одной командой через Nvidia Inspector. Я пробовал использовать встроенные в майнеры опции запуска для разгона GPU - но это не работает всегда корректно.

**Comment by angelbbs** [comment]
Добавлена возможность запуска командных файлов до и после запуска майнеров.
Более подробную инструкцию см. в файлах BeforeMining.cmd и AfterMining.cmd в папках майнеров.

**Comment by foxwarernd** [comment]
Увидел. Большое спасибо!

**Comment by foxwarernd** [comment]
Я отредактировал под себя файлы BeforeMining.cmd и AfterMining.cmd в папках майнеров.
Но при запуске NHML fix содержимое этих файлов возвращается к первоначальному - то есть всё что я ввожу исчезает.

Что это может быть?

**Comment by angelbbs** [comment]
Если имена файлов не меняли, то ничего исчезать не должно

**Comment by foxwarernd** [comment]
Всё заработало. Пытался редактировать папку с которой шла синхронизация и каждый раз файлы возвращались.
Также хочу отметить что путь вида "utils\nvidiaInspector.exe" у меня не сработал - прописал в батнике полный путь.
