### ISSUE TITLE
lolMiner mines on incorrect GPUs

### ISSUE THREAD

**Issue by italianoch** [angelbbs/NiceHashMinerLegacy#53]
It seems like an enumeration issue, but I have a rig of 6 Nvidia/6 AMD. When trying to use lolMiner with the AMD cards, lolMiner incorrectly starts mining on some cards not selected to use it. For example, when I select my 6 V64 cards to run lolMiner BEAM and start mining, it ends up activating 4 Nvidia cards and 2 V64 cards.

**Comment by angelbbs** [comment]
try latest build: https://github.com/angelbbs/NiceHashMinerLegacy/blob/master/LatestBuild/nhmlffLatest.zip
Overwrite existing Fork Fix 13 files

**Comment by woodyalien** [comment]
Same issue here.
I have just updated to 13.1 but still same issue
and in addition to LOLMINER, it happens with GMINER as well.

**Comment by angelbbs** [comment]
in General.json set to true lolMinerOldEnumeration parameter. Then run program again

**Comment by woodyalien** [comment]
It did not resolve the problem.
I cannot say if it changed anything in the ordering but definitely did not resolve the situation.
