### ISSUE TITLE
GMiner can mining BEAM on AMD from now

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#54]
May it is an good idea to implement this in future releases.

> Equihash 150,5: (BEAM)
Palit GTX 1060 Super JetStream 3GB ~11 Sol/s
Palit GTX 1060 JetStream 6GB ~13 Sol/s
Palit GTX 1070 Ti JetStream 8GB ~23 Sol/s
MSI GTX 1080 SEA HAWK EK X 8GB ~24 Sol/s
Gigabyte 1080 Ti AORUS Waterforce WB Xtreme Edition 11GB ~33 Sol/s
MSI RTX 2070 Armor 8GB ~23 Sol/s
MSI RTX 2080 DUKE 8GB ~30 Sol/s
Sapphire VEGA 56 8GB ~18 Sol/s
PowerColor RX580 Red Devil 8GB ~12 Sol/s

**Comment by angelbbs** [comment]
lolminer more profitable at this moment
