### ISSUE TITLE
How to use OverdriveNTool with your batch file... 

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#56]
Is there a guide or something like that?

**Comment by foxwarernd** [comment]
make profile with OverdriveNTool and insert running in block  cmd  :OC 

https://github.com/angelbbs/NiceHashMinerLegacy/wiki/%5BExample%5D-BeforeMining.cmd-overclock-script

**Comment by foxwarernd** [comment]
example run 
OverdriveNTool.exe -p1"RX480_8GB_full" -p2"RX480_4GB_full" -p3"RX480_4GB_full"

**Comment by PeDa1** [comment]
Hmm, I tried this already and do not work on my rig. I have to make the profiles first, right? And the profile names comes between the "", right?

**Comment by foxwarernd** [comment]
exactly

**Comment by PeDa1** [comment]
And is this the correct line, my batch looks a little bit different as your posted example:

> ::utils\OverdriveNTool.exe -p0"****"

`@echo off

rem ****************************************************************************************
rem * Set RUN on TRUE to enable this command scrypt
rem * Установите параметр RUN в TRUE, что бы включить выполнение этого коммандного файла
rem ****************************************************************************************
SET RUN=FALSE

rem ****************************************************************************************
rem * Установите параметр NOVISIBLE в TRUE, что бы скрыть окно выполнения этого коммандного файла
rem * Set NOVISIBLE on TRUE to hide command window
rem ****************************************************************************************
SET NOVISIBLE=FALSE

echo Current algo: %3
rem ****************************************************************************************
rem * Все команды в разделах приведены только для примера
rem * All commands in sections are given for example only
rem * Добавьте свои команды установки профилей разгона и т.п. в необходимые секции
rem * Add your own commands to install overclocking profiles, etc. in necessary sections
rem ****************************************************************************************
cd..
cd..
if "%1" EQU "AMD" goto amd
if "%1" EQU "NVIDIA" goto nvidia
if "%1" EQU "CPU" goto end
goto end

:nvidia
if "%2" EQU "DUAL" goto nvidiadual
rem ****************************************************************************************
rem * MSI Afterburner section for NVIDIA
rem * MSI Afterburner раздел, для исполнения команд для NVIDIA
rem ****************************************************************************************
echo NVIDIA
::start "start "" "C:\Program Files(x86)\MSI Afterburner\MSIAfterburner.exe" -Profile2

rem NVIDIA Inspector section
::utils\nvidiaInspector.exe -setBaseClockOffset:0,0,100 -setMemoryClockOffset:0,0,500 -setPowerTarget:0,95 -setTempTarget:0,0,75 -setFanSpeed:0,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:1,0,100 -setMemoryClockOffset:1,0,500 -setPowerTarget:1,95 -setTempTarget:1,0,75 -setFanSpeed:1,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:2,0,100 -setMemoryClockOffset:2,0,500 -setPowerTarget:2,95 -setTempTarget:2,0,75 -setFanSpeed:2,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:3,0,100 -setMemoryClockOffset:3,0,500 -setPowerTarget:3,95 -setTempTarget:3,0,75 -setFanSpeed:3,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:4,0,100 -setMemoryClockOffset:4,0,500 -setPowerTarget:4,95 -setTempTarget:4,0,75 -setFanSpeed:4,-1
rem ****************************************************************************************
rem * End of MSI Afterburner section for NVIDIA
rem * Конец MSI Afterburner раздела, для исполнения команд для NVIDIA
rem ****************************************************************************************
goto end

:nvidiadual
rem ****************************************************************************************
rem MSI Afterburner section for NVIDIA (claymore dual mode)
rem * MSI Afterburner раздел, для исполнения команд для NVIDIA (claymore dual mode)
rem ****************************************************************************************
echo NVIDIA DUAL
::start "start "" "C:\Program Files(x86)\MSI Afterburner\MSIAfterburner.exe" -Profile2

rem NVIDIA Inspector section
::utils\nvidiaInspector.exe -setBaseClockOffset:0,0,100 -setMemoryClockOffset:0,0,500 -setPowerTarget:0,95 -setTempTarget:0,0,75 -setFanSpeed:0,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:1,0,100 -setMemoryClockOffset:1,0,500 -setPowerTarget:1,95 -setTempTarget:1,0,75 -setFanSpeed:1,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:2,0,100 -setMemoryClockOffset:2,0,500 -setPowerTarget:2,95 -setTempTarget:2,0,75 -setFanSpeed:2,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:3,0,100 -setMemoryClockOffset:3,0,500 -setPowerTarget:3,95 -setTempTarget:3,0,75 -setFanSpeed:3,-1
::utils\nvidiaInspector.exe -setBaseClockOffset:4,0,100 -setMemoryClockOffset:4,0,500 -setPowerTarget:4,95 -setTempTarget:4,0,75 -setFanSpeed:4,-1
rem ****************************************************************************************
rem End of MSI Afterburner section for NVIDIA (claymore dual mode)
rem * Конец MSI Afterburner раздела, для исполнения команд для NVIDIA (claymore dual mode)
rem ****************************************************************************************
goto end

:amd
rem ****************************************************************************************
rem * MSI Afterburner section for AMD
rem * MSI Afterburner раздел, для исполнения команд для AMD
rem ****************************************************************************************
if "%2" EQU "DUAL" goto amddual
echo AMD
rem AMD OverdriveNTool section for AMD only ETH mode
::utils\OverdriveNTool.exe -p0"card1"
::utils\OverdriveNTool.exe -p1"card1"
rem ****************************************************************************************
rem * End of MSI Afterburner section for AMD
rem * Конец MSI Afterburner раздела, для исполнения команд для AMD
rem ****************************************************************************************
goto end

:amddual
rem ****************************************************************************************
rem MSI Afterburner section for AMD (claymore dual mode)
rem * MSI Afterburner раздел, для исполнения команд для AMD (claymore dual mode)
rem ****************************************************************************************
echo AMD DUAL
rem AMD OverdriveNTool section for AMD dual mode
::utils\OverdriveNTool.exe -p0"card1"
::utils\OverdriveNTool.exe -p1"card1"
rem ****************************************************************************************
rem End of MSI Afterburner section for AMD (claymore dual mode)
rem * Конец MSI Afterburner раздела, для исполнения команд для AMD (claymore dual mode)
rem ****************************************************************************************
goto end

:end
echo END
rem Do NOT disable this delay
timeout /t 1 /nobreak
`
