### ISSUE TITLE
Unsupported Miner Version TT Miner

### ISSUE THREAD

**Issue by PBJellytime** [angelbbs/NiceHashMinerLegacy#58]
I have two rigs both with GTX 1060, one benchmarks fine, the other errors on TTMiner saying unsupported version

**Comment by angelbbs** [comment]
log.txt

**Comment by PBJellytime** [comment]
[Log_GPU-b5e0796f-ab15-2f34-8476-c1c5f28c26c8_TTMiner_MTP.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2895691/Log_GPU-b5e0796f-ab15-2f34-8476-c1c5f28c26c8_TTMiner_MTP.txt)

**Comment by angelbbs** [comment]
log.txt from LOGS folder

**Comment by PBJellytime** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2895787/log.txt)

Had to rerun the benchmark sorry

**Comment by angelbbs** [comment]
You use wrong version TT-Miner - Version: 2.1.10 (Feb 13 2019 23:11:20) instead

**Comment by PBJellytime** [comment]
Yeah i downloaded the latest version to see if that would fix it, got the same errors with 2.1.10

**Comment by angelbbs** [comment]
https://tradeproject.de/download/Miner/TT-Miner-2.1.11-beta8.zip

**Comment by PBJellytime** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2895873/log.txt)

Same error using the beta version

**Comment by PBJellytime** [comment]
re-downloaded the whole Fork and still the same error on one rig but not the other
