### ISSUE TITLE
ccminer MTP

### ISSUE THREAD

**Issue by Joshwaa2010** [angelbbs/NiceHashMinerLegacy#59]
Seems on all my rigs that ccminer MTP only the first share submitted works then all others fail to validate on CPU. Then once in a while a share will be submitted but most all fail to validate.  Anyone else having this issue?

**Comment by PBJellytime** [comment]
Yeah had the same issue with one of the other algos that ccminer supports so disabled it

**Comment by nomemega** [comment]
this is undermining your reputation

**Comment by PBJellytime** [comment]
So it appears to be a memory issue with CCMiner and MTP, i can run 4 cards fine but add the 5th and it errors, checked task manager and CCMiner is using 75% of the available memory!
