### ISSUE TITLE
Update CryptoDredge to v0.17.0 and add CryptoDredge Cuckaroo29 algorithm

### ISSUE THREAD

**Issue by qwertydog** [angelbbs/NiceHashMinerLegacy#60]
https://github.com/technobyl/CryptoDredge/releases/tag/v0.17.0

**Comment by angelbbs** [comment]
0.17.0 incompatible with nicehash

**Comment by Oink70** [comment]
I updated to ryptoDredge_0.17.0_cuda_10.0_windows manually and it runs fine here on one of my GPU's (GTX1050)...
