### ISSUE TITLE
Can't compile v13+

### ISSUE THREAD

**Issue by Balzhur** [angelbbs/NiceHashMinerLegacy#61]
В .gitignore у тебя прописаны variables.cs, которые же прописаны в проекте, без этого файла компиляция не проходит, а на гитхабе его нет, т.к. ты его не залил ибо он в исключениях :)

Пофикси, плиз.

**Comment by angelbbs** [comment]
В variables.cs прописаны несколько очевидных констант, которые встречаются в других местах. Если есть понимание, как программа работает, то подставить верные не составит труда.

**Comment by Balzhur** [comment]
А в чем проблема, там что что-то секретное? Зачем выкладывать неполный код, который не компилируется?

Я пересобираю исколючительно из-за двух правок в [статах](https://github.com/angelbbs/NiceHashMinerLegacy/blob/master/NiceHashMiner/Stats/NiceHashStats.cs), выключаю флуд SMA-DATA* ибо логи получаются совершенно нечитабельные. Как вариант - можешь добавить какую-то галку с выключением этого флуда и я не буду ничего компилировать самостоятельно :)

**Comment by angelbbs** [comment]
Ничего секретного, просто защита "от дурака". В следующей версии добавлю отключение статистики в логах.

**Comment by angelbbs** [comment]
Добавил параметр NoShowApiInLog в General.json

**Comment by Balzhur** [comment]
Спасибо!

**Comment by Balzhur** [comment]
Хм... LatestBuild выкидывает эту переменную из конфига. Еще не пересобирал?
