### ISSUE TITLE
2 Problems with Beam mining on AMD

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#62]
Me again, sorry! :|

#1 I get every time if I mining BEAM or switch from to another algorithm or stop the mining on AMD with GMiner this Windows Error Message as follows:

![screenshot](https://user-images.githubusercontent.com/40469299/53443302-ae031680-3a0b-11e9-8544-0f96ba07ea7a.jpg)

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.ComponentModel.Win32Exception (0x80004005): Zugriff verweigert
>    bei System.Diagnostics.Process.Kill()
>    bei NiceHashMiner.Miner.KillProcessAndChildren(Int32 pid) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs:Zeile 464.
>    bei NiceHashMiner.Miner.KillProcessAndChildren(Int32 pid) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs:Zeile 459.
>    bei NiceHashMiner.Miner.Stop_cpu_ccminer_sgminer_nheqminer(MinerStopType willswitch) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs:Zeile 484.
>    bei NiceHashMiner.Miners.GMiner._Stop(MinerStopType willswitch) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\GMiner.cs:Zeile 65.
>    bei NiceHashMiner.Miner.Stop(MinerStopType willswitch) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs:Zeile 436.
>    bei NiceHashMiner.Miner.End() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs:Zeile 445.
>    bei NiceHashMiner.Miners.Grouping.GroupMiner.End() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\GroupMiner.cs:Zeile 79.
>    bei NiceHashMiner.Miners.MiningSession.StopAllMiners() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MiningSession.cs:Zeile 152.
>    bei NiceHashMiner.Miners.MinersManager.StopAllMiners() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MinersManager.cs:Zeile 15.
>    bei NiceHashMiner.Form_Main.StopMining() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:Zeile 1275.
>    bei NiceHashMiner.Form_Main.ButtonStopMining_Click(Object sender, EventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:Zeile 1014.
>    bei System.Windows.Forms.Control.OnClick(EventArgs e)
>    bei System.Windows.Forms.Button.OnClick(EventArgs e)
>    bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    bei System.Windows.Forms.Button.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3190.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> NiceHashMinerLegacy
>     Assembly-Version: 1.9.0.7.
>     Win32-Version: 1.9.0.7.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/NiceHashMinerLegacy.exe.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3190.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> NiceHashMinerLegacy.Common
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/NiceHashMinerLegacy.Common.DLL.
> ----------------------------------------
> System.Runtime
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> Newtonsoft.Json
>     Assembly-Version: 10.0.0.0.
>     Win32-Version: 10.0.3.21018.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/Newtonsoft.Json.DLL.
> ----------------------------------------
> System.Management
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3190.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Numerics
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3160.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
> ----------------------------------------
> System.Data
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3160.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> log4net
>     Assembly-Version: 1.2.15.0.
>     Win32-Version: 1.2.15.0.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/log4net.DLL.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> MessageBoxManager
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/MessageBoxManager.DLL.
> ----------------------------------------
> NiceHashMinerLegacy.Extensions
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/NiceHashMinerLegacy.Extensions.DLL.
> ----------------------------------------
> System.Collections
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll.
> ----------------------------------------
> System.Linq
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll.
> ----------------------------------------
> ManagedNvml
>     Assembly-Version: 8.0.22.0.
>     Win32-Version: 8.0.22.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/ManagedNvml.DLL.
> ----------------------------------------
> PInvokeDelegateFactoryInternalAssembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 1.9.0.7.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/NiceHashMinerLegacy.exe.
> ----------------------------------------
> websocket-sharp
>     Assembly-Version: 1.0.2.35467.
>     Win32-Version: 1.0.2.35467.
>     CodeBase: file:///E:/Mining/NHML.Fork.Fix.13.1/websocket-sharp.DLL.
> ----------------------------------------
> Microsoft.CSharp
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
> ----------------------------------------
> System.Dynamic
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
> ----------------------------------------
> Microsoft.CSharp.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll.
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 4.7.3190.0 built by: NET472REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3056.0 built by: NET472REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

#2 something is wrong again with the GPU enumeration on lolminer. I can´t mining with them ....

**Comment by angelbbs** [comment]
1. Update .NET framework
2. in General.json set to true lolMinerOldEnumeration parameter. Then run program again

**Comment by PeDa1** [comment]
> 
> 
>     1. Update .NET framework
> 
>     2. in General.json set to true lolMinerOldEnumeration parameter. Then run program again

1. do not work, unfortunately.
2. that works, perfect!
