### ISSUE TITLE
CryptoNightR, no shares with SRBminer ... 

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#63]
@angelbbs, unfortunately I find no share if I mining with SRBminer. The hashrate is very high and no failure message and other algorithm are quiet stable.

**Comment by electricdelicate** [comment]
So, after a reinstall, the SRBminer do not start anymore. Please investigate, something is wrong.

**Comment by angelbbs** [comment]
What OS, GPU etc...

**Comment by electricdelicate** [comment]
Windows 10 x64
1x RX480
1x RX570
1x Vega
1x GTX1070

[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2953499/log.txt)

**Comment by electricdelicate** [comment]
@angelbbs, do you have find already the problem?

**Comment by angelbbs** [comment]
no

**Comment by electricdelicate** [comment]
I´ve limited the problem, after reinstall again and a Benchmark run over all, at least the SRBminer starts again, luckily. 
Now is the first problem occur again, i got absolutely no (valid) shares when the miner mining CryptoNightR on my Vega64, the other cards runs good with the miner. And all the other algorithm and miner runs really stable and fast on the Vega64. 

May a problem with the miner, not with your GUI. Let us see ....

**Comment by angelbbs** [comment]
))
