### ISSUE TITLE
Проблема бенчмарков

### ISSUE THREAD

**Issue by foxwarernd** [angelbbs/NiceHashMinerLegacy#64]
При проведении бенчмарков есть проблемы:
1) Результат бенчмарка разнится с тем что на самом деле
2) На некоторых алгоритмах бенчмарк вообще не проходит, но майнинг работает

Всё это происходит из за бенчмарка не на nicehash, а на сторонних пуллах.

Я понимаю что надо как то автора стимулировать, но чтобы было хорошо надо делать хорошо

**Comment by angelbbs** [comment]
1. Покажите в логах и скринах, где разница?
2. Опять же, какие алгоритмы, какие карты, какая ОС, какие драйверы. Где логи?

**Comment by foxwarernd** [comment]
Не ищите оправданий там где их нет. Это я наблюдаю уже не один месяц и на многих ваших версиях.
Логи и скрины приведу. Но вы как доработчик, а главное модификатор nhm должны понимать о чём я говорю

**Comment by angelbbs** [comment]
Можете наблюдать сколько угодно. Без логов и скринов это всё пустые слова.

**Comment by foxwarernd** [comment]
А с логами и скринами по моим просьбам Вы не разу не шевелились )

**Comment by foxwarernd** [comment]
Вопрос: проводя бенчмарк на одном пуле с другой сложностью можно сказать  что примерно совпадут результаты с nicehash майнингом?

**Comment by foxwarernd** [comment]
Не хотелось бы здесь всё это обсуждать. Как я могу переписываться с Вами приватно?

**Comment by angelbbs** [comment]
@foxwarernd Да, на всех майнерах, на всех алгоритмах, на любых картах, кроме старых amd до поляриса на даггере.

**Comment by angelbbs** [comment]
Нет, если есть обоснованные претензии, то они должны обсуждаться открыто.

**Comment by foxwarernd** [comment]
Бенчмарк:
![image](https://user-images.githubusercontent.com/19841581/54479691-95c73000-4830-11e9-9476-befe6bc734b0.png)

![image](https://user-images.githubusercontent.com/19841581/54479699-b5f6ef00-4830-11e9-969b-3581ab116d04.png)


Майнинг на nicehash:

![image](https://user-images.githubusercontent.com/19841581/54479722-edfe3200-4830-11e9-88d6-28b1e16227f5.png)

![image](https://user-images.githubusercontent.com/19841581/54479725-feaea800-4830-11e9-93d6-7c44eed01fa6.png)

![image](https://user-images.githubusercontent.com/19841581/54479732-0e2df100-4831-11e9-9d93-29a3b982e1cd.png)

**Comment by foxwarernd** [comment]
по сути автоматический бенчмарк вроде и есть и вроде его нет. приходится по всему руками проходить и тестировать каждый алго в отдельности. нет, я не спорю мои сложности. но всё таки нельзя ли сделать тест майнинга на пуллах найса с моих адресом btc? я не против поделится немного майнингом, но так чтобы мне тоже было удобно.

**Comment by foxwarernd** [comment]
[log.1.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2974185/log.1.txt)
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/2974186/log.txt)

**Comment by foxwarernd** [comment]
![image](https://user-images.githubusercontent.com/19841581/54479809-281c0380-4832-11e9-9c45-717e87394d2f.png)

![image](https://user-images.githubusercontent.com/19841581/54479813-39651000-4832-11e9-97e8-dce0fd1d53ff.png)

**Comment by YuriyNa** [comment]
> Нет, если есть обоснованные претензии, то они должны обсуждаться открыто.

Надо бы найти другой ресурс, раз битсмедиа стал недоступен. Конечно это вам решать, хотите ли вы дальше конкурировать с официальным легаси. Сейчас они начали исправляться хотя пока от вас отстают))))).

**Comment by angelbbs** [comment]
@foxwarernd В логах видно, что бенчмарк на эфире ~19MH/s
[2019-03-16 21:16:20] [INFO] [BENCHMARK] 21:16:13:283	1f7c	eth - total speed: 19.492 mh/s, total shares: 0, rejected: 0, time: 00:00
[2019-03-16 21:16:20] [INFO] [BENCHMARK] 21:16:13:283	1f7c	eth: gpu0 19.492 mh/s

**Comment by foxwarernd** [comment]
почему тогда с бенчмарка проставляется 23 MH/s в итоге?

**Comment by angelbbs** [comment]
@foxwarernd Отключите разгон в BeforeMining.cmd, если он есть и пройдите бенчмарк еще раз на обеих картах одновременно, затем покажите скрин экрана целиком с открытым файлом log.txt, где будет видно скорость бенчмарка.

**Comment by angelbbs** [comment]
@YuriyNa В текущий момент нет смысла в выпуске новых версий или доработке старых. После того как найс выпустит версию с поддержкой плагинов, будет новая версия форка. Когда это случится - неизвестно.

**Comment by angelbbs** [comment]
@foxwarernd И кстати, разберитесь, чем у Вас карты еще заняты, ибо для 1080 19 МХ/с маловато будет )))

**Comment by YuriyNa** [comment]
> @YuriyNa В текущий момент нет смысла в выпуске новых версий или доработке старых. После того как найс выпустит версию с поддержкой плагинов, будет новая версия форка. Когда это случится - неизвестно.

Да я не о новой версии, я об обсуждении. Пропала связь с Вами, это нехорошо(((((

**Comment by angelbbs** [comment]
> Да я не о новой версии, я об обсуждении. Пропала связь с Вами, это нехорошо(((((
> "Это зависит от автора))))). Нам то ветка полюбому нужна))))). Но автор пока молчит. Хотя альтернативу этому форуму найти конечно можно."
Я не молчу, просто по глупому совпадению никуда написать не могу. ))) Форум нужен, но я пока не занимался выбором площадки для него, нету времени и желания. Новые версии будут. Составлен todo list, в котором добавление новых майнеров, реализация новых фич, исправление старых ошибок и добавление новых. )))) Думаю, в новых версиях мне будет чем порадовать пользователей программы))

PS И кстати, в личке ВК связь со мной есть всегда.

**Comment by angelbbs** [comment]
@foxwarernd Вы разобрались со своей проблемой? Тему можно закрывать?

**Comment by nomemega** [comment]
а  как решить проблему с запуском gminer , то есть когда одна копия майнера незакрылась а другая копия майнера запустилась на техже картах ?

**Comment by angelbbs** [comment]
@nomemega На какой версии это происходит?

**Comment by nomemega** [comment]
в данный момент стоит 14,1  и только на ней т,к   две карты 1080 и две 1060    пока попробывал в майнере изменить файл  AfterMining  и прописал туда команды    из   AfterBenchmark

**Comment by nomemega** [comment]
то есть проше говоря не всегда  происходит закрытие майнера gminer  и запускаеться ещё одна копия майнера gminer  с тем же алгоритмом     и ето можно заметить в статистеке найса   когда одна установка майнит  4 разных парных алгоритмов

**Comment by angelbbs** [comment]
@nomemega уменьшайте разгон

**Comment by nomemega** [comment]
![0](https://user-images.githubusercontent.com/34583991/54487819-73262d00-48ab-11e9-995d-70048273ee4d.jpeg)

**Comment by nomemega** [comment]
да дело в не разгоне   дело почему майнер невсегда  закрываеться    и стартует с другими майнерами   пример на картинке

**Comment by nomemega** [comment]
таесть копия майнера запускаеться       и помогает только    полное закрытия  найс хеш

**Comment by nomemega** [comment]
нет ошибок реджектов   карты неотваливаються

**Comment by angelbbs** [comment]
@nomemega Майнер может не закрываться при переразгоне

**Comment by nomemega** [comment]
да у меня разгон  то +100 ядро  +450 память P0   и фиксированная  напряжение 0.950

**Comment by nomemega** [comment]
ерунда какае та  gminer  запускаеться с другими майнерами

**Comment by lexayar** [comment]
Согласен с foxwarernd. Посмотрел исходники. Не хорошо, что бэнчмарк делается на сторонних пулах.

**Comment by angelbbs** [comment]
@lexayar Не будет бенчмарков - не будет программы.

**Comment by lexayar** [comment]
@angelbbs, отличный ответ разработчика )) Я понимаю, что вам и так с этих бенчмарков не много капает. Но какой смысл в программе, если она выбирает не профитные алгоритмы. Боремся за какие-то мелочи профита путем использования альтернативных майнеров, но при этом копаем то, что не профитно на пуле найсхеша. Я не говорю, чтоб совсем отменить бенчмарки, но почему нельзя их выполнять на пуле найсхеша?

**Comment by foxwarernd** [comment]
@angelbbs пока не было времени детально посмотреть

@lexayar не стоит давить на @angelbbs. то что он делает хорошо

**Comment by lexayar** [comment]
@foxwarernd не хотел кого-то обидеть. Но хочется чтоб всем было хорошо и разработчику и пользователям))

**Comment by angelbbs** [comment]
@lexayar 1. Хешрейт майнеров не зависит от того, проходит ли бенчмарк на найсе или на других пулах.
2. Бенчмарки на найсе выполнять нельзя, потому что это уже проходили, найс блокирует кучу ip с которых идет бенчмарк на один адрес.

**Comment by lexayar** [comment]
1. В идеальных условиях не должен. @foxwarernd написал, что разница есть. Я сам лично не проверял. Хорошо, если не влияет, тогда претензий нет. Но отчего тогда у меня даже на одном и том же пуле хешрейт в течение дня прилично (процентов на 20%) меняется.
2. Теперь понятно

**Comment by angelbbs** [comment]
@lexayar А это вопрос уже к майнеру, как у него внутри хешрейт считается.
