### ISSUE TITLE
No Grin29 mining possible ....

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#65]
... on my new RTX2060. With my GTX1070 without any problems.
![screenshot](https://user-images.githubusercontent.com/40469299/55401461-1edca780-5551-11e9-9500-b01bc8f92b38.jpg)

[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/3033796/log.txt)

And almost forgotten, it works with the original Legacy miner.

**Comment by YuriyNa** [comment]
> ... на моем новом RTX2060. С моим GTX1070 без проблем.
> ![скриншот](https://user-images.githubusercontent.com/40469299/55401461-1edca780-5551-11e9-9500-b01bc8f92b38.jpg)
> 
> [бревно.формат txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/3033796/log.txt)

out of memory!!!!!!!

**Comment by electricdelicate** [comment]
And why? Have the RTX2060 to little VRAM? As I wrote before, the GTX1070 runs without any problems.

**Comment by YuriyNa** [comment]
> И почему? Есть RTX2060 к маленькой VRAM? Как я уже писал ранее, GTX1070 работает без каких-либо проблем.
GTX1070 8GB of video memory, RTX2060 6GB of video memory. Few.

**Comment by electricdelicate** [comment]
> 
> 
> > И почему? Есть RTX2060 к маленькой VRAM? Как я уже писал ранее, GTX1070 работает без каких-либо проблем.
> > GTX1070 8GB of video memory, RTX2060 6GB of video memory. Few.

But Grin Mining should be possible on 6GB cards, also on the RTX2060!

**Comment by angelbbs** [comment]
@electricdelicate  Only in Windows 7. Read more detailed dev forum.

**Comment by electricdelicate** [comment]
Thank you guys, now it works!
![grafik](https://user-images.githubusercontent.com/40469299/55930362-266f1100-5c21-11e9-9a3c-7fbee0e9623d.png)
