### ISSUE TITLE
Name Identifier String

### ISSUE THREAD

**Issue by PrinceOfParallax** [angelbbs/NiceHashMinerLegacy#67]
I have no way to tell what each device is when I moved a card from PC to PC or even do maintence on the PC - can the miner put part of the UUID or something in the strings so we can track the cards a little better.

eg current:
  "DeviceUUID": "PCI_VEN_1002&DEV_67DF_7D7BB99",
  "DeviceName": "Radeon RX 580 Series",

  Change:
  "DeviceUUID": "PCI_VEN_1002&DEV_67DF_7D7BB99",
  "DeviceName": "Radeon RX 580 Series- BB99",

**Comment by foxwarernd** [comment]
nice to add to the name of the amount of memory:
"DeviceName": "Radeon RX 580 Series (8Gb) - BB99",
