### ISSUE TITLE
Incompatibility with *New* Nicehash site.

### ISSUE THREAD

**Issue by PrinceOfParallax** [angelbbs/NiceHashMinerLegacy#70]
As per the comments by Andrej the system/site is not compatible without NiceHash Miner 1.9.2.6. Can we bring fork to compliance with what ever protocols the site is using so we can continue to use fork?

**Comment by angelbbs** [comment]
yes, later

**Comment by Joshwaa2010** [comment]
Is the new site more profitable yet?  I tried it 2 days ago and it was earning less than old platform.

**Comment by PrinceOfParallax** [comment]
> Is the new site more profitable yet? I tried it 2 days ago and it was earning less than old platform.

Thank you for adding - only thing might work better is auto switching between for better Profits... but I bet that takes some hard work. <3
