### ISSUE TITLE
Remove unprovitable algorithm

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#71]
.... some of the older algorithm should be removed.

Thanks!

**Comment by PrinceOfParallax** [comment]
No they should stay, as they can be profitable for some rigs, or if a coin/algo makes a come back.

**Comment by electricdelicate** [comment]
For sure, do you think the older cryptonight versions, for example, have a come back? I don't think so!

**Comment by PrinceOfParallax** [comment]
If you don't like that Algo - then don't use them. Many Algo has made comes backs.
