### ISSUE TITLE
request API bytes

### ISSUE THREAD

**Issue by luc1an24** [angelbbs/NiceHashMinerLegacy#73]
Hi
Would you please mind sharing with me which bytes do you send to tcp client to get MiniZ API data?
In the https://github.com/angelbbs/NiceHashMinerLegacy/blob/6d8d27f3128e9ad3e69e911c60e5bf9cb59f42a9/NiceHashMiner/Miners/miniZ.cs#L401
 line.
Thank you

**Comment by angelbbs** [comment]
https://bitcointalk.org/index.php?topic=4767892.0
