### ISSUE TITLE
BTC value won´t updated

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#74]
its curious, since one hour no update of the btc-value if I choose the new platform.
If I take the old platform, the value is correct. 
![1111111](https://user-images.githubusercontent.com/40469299/62221528-10dd4d00-b3b2-11e9-8bbd-bb2fa324c376.jpg)

**Comment by angelbbs** [comment]
on new platform program shown only unpaid balance, not btc in wallet
