### ISSUE TITLE
MTP connection to pool timing out on every pool

### ISSUE THREAD

**Issue by PBJellytime** [angelbbs/NiceHashMinerLegacy#75]
As per the title I've had to disable TTMiner as it seems unable to find a pool using Fork Fix 16 on the new platform

**Comment by angelbbs** [comment]
MTP missing on new platform

**Comment by PBJellytime** [comment]
Thanks, thought that was it but couldn't find any details on it

**Comment by angelbbs** [comment]
Nicehash has suddenly become to give on profitability of the MTP on a new platform that is missing. As a result, MTP mining on new platform may be enabled. I recommend to disable MTP on new platform, if it was enabled.
