### ISSUE TITLE
Suggestion: Dark mode

### ISSUE THREAD

**Issue by nerdatwork** [angelbbs/NiceHashMinerLegacy#80]
Having dark mode for entire NHM.

**Comment by angelbbs** [comment]
for what purpose?

**Comment by sinnx3** [comment]
> for what purpose?

Some people prefer a dark theme as opposed to a light (current) theme because it's easier on the eyes. (And truthfully you'd 1up NH on this if implemented as users have been begging for this feature for years.)

**Comment by angelbbs** [comment]
https://mega.nz/#!WQIDRCYT!rsCpr3nv03alnN1iozKQ-EHflZVpybjgnodDMi18Ykw
