### ISSUE TITLE
Feature Request: Disable All or certain GPU stats (temp, load, fan, power)

### ISSUE THREAD

**Issue by davidhonasan** [angelbbs/NiceHashMinerLegacy#82]
Hi, is it possible to add feature to disable certain stats or all stats? (temp, load, fan, power)
the GPU stats polling (polling seems too fast) seems to slow down and crashes the miner. Thanks

**Comment by angelbbs** [comment]
this monitoring has always been and does not affect miners

**Comment by davidhonasan** [comment]
or is it possible to add feature to set the polling interval?
