### ISSUE TITLE
not detecting gtx 1660 fork fix 20.1

### ISSUE THREAD

**Issue by professor-jonny** [angelbbs/NiceHashMinerLegacy#84]
as prer title it is not detecting my gtx 1660 in fork fox 20.1 I have the latest nividia driver and it worked in fork fix 20 with no issue

**Comment by angelbbs** [comment]
try copy nvml.dll from FF 20 to FF 20.1 folder

**Comment by professor-jonny** [comment]
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/3992359/log.txt)

**Comment by professor-jonny** [comment]
copying the file fixed the problem thanks
