### ISSUE TITLE
After new card installation, lolMiner take the wrong card!

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#86]
Hello,

after installing of a new card on my rig, lolMiner do not take my Radeon VII anymore. It seems he choose one of the other nVidia cards. After initalizing lolMiner quit they instance and restarts again and again in a endless loop.

Thank you in advance!
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/4208849/log.txt)

**Comment by angelbbs** [comment]
set lolMinerOldEnumeration to true or false in General.json, then run program

**Comment by electricdelicate** [comment]
Hi, I solved the issue different, by reinstalling the AMD Driver. Curious that I must reinstall also the AMD Driver even though I add an nVidia card. 

Now lolMiner works correctly! :)
