### ISSUE TITLE
GrinCuckarood29 don´t start with lolMiner on AMD

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#89]
Hi,

since version 0.9.8, the miner don´t start on my Rig, if they want to mine GrinCuckarood29 .
The other algorithm works fine with the miner.

Any ideas?
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/4430972/log.txt)

**Comment by angelbbs** [comment]
run lolminer from command prompt and make screenshot:
lolminer --coin GRIN-AD29 --pool grincuckarood29.eu.nicehash.com;grincuckarood29.usa.nicehash.com;grincuckarood29.hk.nicehash.com;grincuckarood29.jp.nicehash.com;grincuckarood29.in.nicehash.com;grincuckarood29.br.nicehash.com --port 3377;3377;3377;3377;3377;3377 --user 39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA;39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA;39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA;39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA;39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA;39d2gVnrTCRyUKxdWUiTtHjyiYjm5Z6nsC.RIG$0-AeN556ssy1W0gYGGHYqUpA -p x;x;x;x;x;x --tls 0;0;0;0;0;0 --apiport 4002 --asm 1 --devices 3

**Comment by electricdelicate** [comment]
Hi,

unfortunately don´t work:
![1](https://user-images.githubusercontent.com/40469299/78433702-13492280-7676-11ea-9928-a7c4a1b1d31b.JPG)

Regards,
Peter
