### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#90]
What do you think about an Start/Stop button next to the restart button for example.
![grafik](https://user-images.githubusercontent.com/40469299/78422730-c65b5100-7661-11ea-87c3-bcf8da6928cf.png)
Is that possible to realise?

**Comment by angelbbs** [comment]
What for?

**Comment by electricdelicate** [comment]
Hi again,

for easier handling if I choice to mining with my CPU for example.
I believe, the origin NiceHash Miner have this already.

Your decision, is only an proposal from my side. 😊
