### ISSUE TITLE
NBMiner always takes the wrong (AMD) card on mixed rig.

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#91]
see the attached picture:
![grafik](https://user-images.githubusercontent.com/40469299/78422885-eb03f880-7662-11ea-8383-ad06efdd3e0a.png)
Probably wrong enumeration in combination with AMD, please fix that as soon as possible.
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/4431024/log.txt)

Thank you!

**Comment by angelbbs** [comment]
try General.json -> "OverrideAMDBusIds": "46,49,50",

**Comment by electricdelicate** [comment]
Don´t work. :(
[log.txt](https://github.com/angelbbs/NiceHashMinerLegacy/files/4431291/log.txt)

**Comment by angelbbs** [comment]
https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip

**Comment by electricdelicate** [comment]
wow, it seems to work!

Great job mate! :)

**Comment by angelbbs** [comment]
rx5700 and Vega began to show temperature etc.?

**Comment by electricdelicate** [comment]
No.

![grafik](https://user-images.githubusercontent.com/40469299/78457412-46a5a480-76aa-11ea-8a40-2b033a82fa8a.png)

**Comment by electricdelicate** [comment]
Hi again,
I get, since your update, after hours of mining this eror message:
![grafik](https://user-images.githubusercontent.com/40469299/78668043-50adea00-78da-11ea-8260-c3246ff94448.png)
Sorry is in german!

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.InvalidOperationException: Das Objekt mit Nullwert muss einen Wert haben.
>    bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    bei System.Nullable`1.get_Value()
>    bei NiceHashMiner.Devices.AmdComputeDevice.get_Load() in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\AmdComputeDevice.cs:Zeile 134.
>    bei NiceHashMiner.Forms.Components.DevicesListViewEnableControl.SetComputeDevicesStatus(List`1 computeDevices) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs:Zeile 189.
>    bei NiceHashMiner.Form_Main.DeviceStatusTimer_Tick(Object sender, EventArgs e) in D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs:Zeile 1988.
>    bei System.Windows.Forms.Timer.OnTick(EventArgs e)
>    bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> NiceHashMinerLegacy
>     Assembly-Version: 1.0.7399.31525.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4001.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> NiceHashMinerLegacy.Common
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.Common.DLL.
> ----------------------------------------
> System.Runtime
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> Newtonsoft.Json
>     Assembly-Version: 10.0.0.0.
>     Win32-Version: 10.0.3.21018.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/Newtonsoft.Json.DLL.
> ----------------------------------------
> System.Management
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Numerics
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
> ----------------------------------------
> System.Data
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4121.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> log4net
>     Assembly-Version: 1.2.15.0.
>     Win32-Version: 1.2.15.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/log4net.DLL.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> MessageBoxManager
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/MessageBoxManager.DLL.
> ----------------------------------------
> NiceHashMinerLegacy.Extensions
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.Extensions.DLL.
> ----------------------------------------
> System.Collections
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll.
> ----------------------------------------
> System.Linq
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll.
> ----------------------------------------
> NiceHashMinerLegacy.UUID
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.UUID.DLL.
> ----------------------------------------
> BouncyCastle.Crypto
>     Assembly-Version: 1.8.5.0.
>     Win32-Version: 1.8.19031.1.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/BouncyCastle.Crypto.DLL.
> ----------------------------------------
> ManagedNvml
>     Assembly-Version: 8.0.22.0.
>     Win32-Version: 8.0.22.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/ManagedNvml.DLL.
> ----------------------------------------
> PInvokeDelegateFactoryInternalAssembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.exe.
> ----------------------------------------
> OpenHardwareMonitorLib
>     Assembly-Version: 0.8.0.0.
>     Win32-Version: 0.8.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/OpenHardwareMonitorLib.DLL.
> ----------------------------------------
> Microsoft.CSharp
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
> ----------------------------------------
> System.Dynamic
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
> ----------------------------------------
> Microsoft.CSharp.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll.
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
> ----------------------------------------
> websocket-sharp
>     Assembly-Version: 1.0.2.21530.
>     Win32-Version: 1.0.2.21530.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/websocket-sharp.DLL.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> PInvokeDelegateFactoryInternalAssembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 0.8.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/OpenHardwareMonitorLib.dll.
> ----------------------------------------
> NiceHashMinerLegacy.Divert
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 1.0.0.0.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/NiceHashMinerLegacy.Divert.DLL.
> ----------------------------------------
> WinDivertSharp
>     Assembly-Version: 1.4.3.3.
>     Win32-Version: 1.4.3.3.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/WinDivertSharp.DLL.
> ----------------------------------------
> netstandard
>     Assembly-Version: 2.0.0.0.
>     Win32-Version: 4.8.3752.0.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll.
> ----------------------------------------
> JacksonSoft.CustomTabControl
>     Assembly-Version: 1.0.1.7.
>     Win32-Version: 1.0.1.7.
>     CodeBase: file:///D:/Mining/NHML%20Fork%20Fix/JacksonSoft.CustomTabControl.DLL.
> ----------------------------------------
> System.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3752.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by angelbbs** [comment]
https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip

**Comment by electricdelicate** [comment]
Great, I will test the new version.
But the power consumption is still wrong:
![grafik](https://user-images.githubusercontent.com/40469299/78791701-80c7bc80-79b0-11ea-9378-ffb2f28b3149.png)
