### ISSUE TITLE
ver 26, wrong worker name

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#93]
![grafik](https://user-images.githubusercontent.com/40469299/80697555-68435180-8ad9-11ea-9c48-3f2819da59a1.png)

![grafik](https://user-images.githubusercontent.com/40469299/80697462-434ede80-8ad9-11ea-98a8-d8cb28584f83.png)

**Comment by angelbbs** [comment]
Clear "MachineGuid" param in General.json
