### ISSUE TITLE
OpenHardwareMonitor

### ISSUE THREAD

**Issue by PBJellytime** [angelbbs/NiceHashMinerLegacy#94]
I believe NHML has switched over to using OpenHardwareMonitor as of Version 27?  This is an old unsupported piece of software which I have been using for a powershell monitoring script for several years.  However it doesn't recognise any of the P10x mining specific cards so temperature etc is now blank.
![NHML Ver 27](https://user-images.githubusercontent.com/36086338/81651564-acfcb000-942a-11ea-8e4a-72e7ac04e8ba.jpg)

**Comment by angelbbs** [comment]
Uncheck "Use Openhardwaremonitor" in Settings

**Comment by PBJellytime** [comment]
Haha, brilliant. Note to self to check settings first next time!
