### ISSUE TITLE
Ver 29, outdated miniZ version ...

### ISSUE THREAD

**Issue by electricdelicate** [angelbbs/NiceHashMinerLegacy#96]
They don´t work properly with Nicehash at me!
v3 is relased!
![grafik](https://user-images.githubusercontent.com/40469299/86043250-b5e02a00-ba48-11ea-8bb8-266a3a3b00d4.png)

**Comment by angelbbs** [comment]
Delete Fork_Fix_29.txt from Miners folder, then run program
