### ISSUE TITLE
AMD RADEON VII

### ISSUE THREAD

**Issue by BANZAI-616** [angelbbs/NiceHashMinerLegacy#97]
Сделайте распознавание оборотов температуры карты AMD RADEON VII, до сих пор никто не добавил, одни прочерки. И переделайтеопределение видео памяти её, она указана в окне форума как 15gb а она 16gb видеопамяти. Спасибо

**Comment by angelbbs** [comment]
Enable "Use OpenHardwareMonitor"

**Comment by BANZAI-616** [comment]
> Enable "Use OpenHardwareMonitor"

Это тут вообще не причём, эта Галочка отвечает что инфа о картах пойдёт на приложение от Антона Волкова а не на найсхешь! В самом Найс форк да и обычном найсе программа не видит темпер и обороты соответственно передавать нечего. А вот клеймор и афтобернер видит инфу о Р7( Radeon vii)

**Comment by angelbbs** [comment]
Эта галочка отвечает за то, что информация о оборудовании будет считываться OHM, а не программой

**Comment by BANZAI-616** [comment]
> Эта галочка отвечает за то, что информация о оборудовании будет считываться OHM, а не программой

Да спасибо действительно помогло, я перепутал значит. Все стало показывать кроме оборотов, но это не беда
